// examples/react/src/App.tsx
import { useMemo, useState } from "react";
import {
  Badge,
  Button,
  ButtonGroup,
  Card,
  Checkbox,
  ColorPicker,
  Dialog,
  Divider,
  Dropdown,
  FlowUIProvider,
  HC,
  Icon,
  Image,
  Input,
  Label,
  Menu,
  PasswordInput,
  RadioGroup,
  Section,
  Slider,
  Switch,
  Tab,
  Table,
  Tabs,
  TextArea,
  Tooltip,
  Tree,
  TreeDropdown,
  VC,
  createTheme,
  type DialogPosition,
  type DropdownModel,
  type MenuItem,
  type SortState,
  type TableColumn,
  type TreeModel,
} from "@akin2unde/flowui-react";

const theme = createTheme({
  palette: {
    primary: {
      500: "#7c3aed",
      600: "#6d28d9",
      700: "#5b21b6",
    },
  },
});

const menuItems: MenuItem[] = [
  {
    id: "new",
    label: "New product",
    icon: "fa-solid fa-plus",
  },
  {
    id: "messages",
    label: "Messages",
    icon: "fa-solid fa-envelope",
    badge: 4,
  },
  {
    id: "separator",
    label: "",
    separator: true,
  },
  {
    id: "delete",
    label: "Delete",
    icon: "fa-solid fa-trash",
  },
];

const countries: DropdownModel[] = [
  {
    display: "Nigeria",
    value: "ng",
    other: { phoneCode: "+234" },
  },
  {
    display: "United Kingdom",
    value: "uk",
    other: { phoneCode: "+44" },
  },
];

const tree: TreeModel[] = [
  {
    display: "Nigeria",
    value: "ng",
    other: { type: "country" },
    children: [
      {
        display: "Lagos",
        value: "lagos",
        other: { type: "state" },
      },
      {
        display: "Abuja",
        value: "abuja",
        other: { type: "city" },
      },
    ],
  },
  {
    display: "United Kingdom",
    value: "uk",
    other: { type: "country" },
    children: [
      {
        display: "London",
        value: "london",
        other: { type: "city" },
      },
    ],
  },
];

const products: Record<string, unknown>[] = [
  { name: "Rice", category: "Food", price: 42000 },
  { name: "Vegetable oil", category: "Food", price: 18500 },
  { name: "Detergent", category: "Home", price: 9300 },
];

const columns: TableColumn<Record<string, unknown>>[] = [
  {
    field: "name",
    header: "Product",
    sortable: true,
  },
  {
    field: "category",
    header: "Category",
    sortable: true,
  },
  {
    field: "price",
    header: "Price",
    sortable: true,
    align: "right",
    format: (value) => `₦${Number(value).toLocaleString()}`,
  },
];

export function App() {
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [notes, setNotes] = useState("");
  const [checked, setChecked] = useState(true);
  const [notifications, setNotifications] = useState(true);
  const [volume, setVolume] = useState(40);
  const [status, setStatus] = useState("active");
  const [color, setColor] = useState("#6d28d9");
  const [country, setCountry] = useState<string | number>("ng");
  const [location, setLocation] = useState<string | number>("lagos");
  const [treeValue, setTreeValue] = useState<string | number>("lagos");
  const [sort, setSort] = useState<SortState>({
    field: "name",
    direction: "asc",
  });
  const [dialog, setDialog] = useState<DialogPosition | null>(null);

  const sorted = useMemo(() => {
    return [...products].sort((first, second) => {
      if (!sort.direction) return 0;

      const result = String(first[sort.field]).localeCompare(
        String(second[sort.field]),
        undefined,
        { numeric: true },
      );

      return sort.direction === "asc" ? result : -result;
    });
  }, [sort]);

  return (
    <FlowUIProvider theme={theme} mode="system">
      <main className="fui-page">
        <VC
          maxWidth="80rem"
          marginX="auto"
          padding={{ default: "md", md: "xl" }}
          gap="lg"
        >
          <VC gap="xs">
            <Label fontSize="3xl" fontWeight="bold">
              FlowUI React Gallery
            </Label>
            <Label textColor="textMuted">
              Every FlowUI component in one working example.
            </Label>
          </VC>

          <Card
            variant="elevated"
            header={
              <Label fontSize="xl" fontWeight="bold">
                Card, layout, label, icon, badge and image
              </Label>
            }
            footer={<Label textColor="textMuted">Reusable card footer</Label>}
          >
            <HC
              direction={{ default: "column", md: "row" }}
              align="center"
              gap="lg"
            >
              <Image
                src="https://picsum.photos/320/180"
                alt="Sample landscape"
                width={{ default: "full", md: 320 }}
                height={180}
                cornerRadius="lg"
              />

              <VC gap="sm" flex={1}>
                <HC gap="sm" align="center">
                  <Icon
                    icon="fa-solid fa-layer-group"
                    textColor="primary.600"
                  />
                  <Label>Horizontal container</Label>
                  <Badge icon="fa-solid fa-check">Ready</Badge>
                </HC>

                <Label lines={1}>
                  This deliberately long label demonstrates single-line
                  truncation when its available width becomes limited.
                </Label>

                <Divider label="or" />

                <HC height={30} gap="md">
                  <span>Left</span>
                  <Divider orientation="vertical" />
                  <span>Right</span>
                </HC>
              </VC>
            </HC>
          </Card>

          <section className="fui-demo-card">
            <VC gap="md">
              <Label fontSize="xl" fontWeight="bold">
                Buttons, groups and tooltips
              </Label>

              <HC wrap="wrap" gap="sm">
                <Button icon="fa-solid fa-floppy-disk">Save</Button>
                <Button
                  variant="outline"
                  color="secondary"
                  icon="fa-solid fa-arrow-right"
                  iconPosition="right"
                >
                  Continue
                </Button>
                <Button variant="soft" color="success" badge={3}>
                  Approved
                </Button>
                <Button
                  variant="ghost"
                  color="danger"
                  icon="fa-solid fa-trash"
                  iconPosition="center"
                  ariaLabel="Delete"
                />
              </HC>

              <ButtonGroup>
                <Button>Day</Button>
                <Button variant="outline">Week</Button>
                <Button variant="outline">Month</Button>
              </ButtonGroup>

              <HC wrap="wrap" gap="lg">
                {(["top", "right", "bottom", "left"] as const).map(
                  (locationValue) => (
                    <Tooltip
                      key={locationValue}
                      text={`Shown on ${locationValue}`}
                      location={locationValue}
                    >
                      <Button variant="outline">{locationValue}</Button>
                    </Tooltip>
                  ),
                )}
              </HC>
            </VC>
          </section>

          <section className="fui-demo-card">
            <VC gap="md">
              <Label fontSize="xl" fontWeight="bold">
                Form controls
              </Label>

              <Label htmlFor="product-name" required>
                Product name
              </Label>
              <Input
                id="product-name"
                value={name}
                placeholder="Enter product name"
                onChange={(event) => setName(event.target.value)}
              />
              <PasswordInput
                value={password}
                placeholder="Enter password"
                onChange={(event) => setPassword(event.target.value)}
              />
              <TextArea
                value={notes}
                placeholder="Notes"
                onChange={(event) => setNotes(event.target.value)}
              />

              <HC wrap="wrap" gap="lg">
                <Checkbox
                  label="Available for sale"
                  checked={checked}
                  onChange={(event) => setChecked(event.target.checked)}
                />
                <Switch
                  label="Enable notifications"
                  checked={notifications}
                  onChange={setNotifications}
                />
                <ColorPicker
                  value={color}
                  onChange={(event) => setColor(event.target.value)}
                />
              </HC>

              <RadioGroup
                name="status"
                value={status}
                orientation="horizontal"
                options={[
                  { label: "Active", value: "active" },
                  { label: "Inactive", value: "inactive" },
                ]}
                onChange={setStatus}
              />

              <Slider value={volume} onChange={setVolume} />

              <Dropdown
                value={country}
                options={countries}
                onChange={(model) => setCountry(model.value)}
              />

              <TreeDropdown
                value={location}
                options={tree}
                onChange={(model) => setLocation(model.value)}
              />
            </VC>
          </section>

          <section className="fui-demo-card">
            <VC gap="md">
              <Label fontSize="xl" fontWeight="bold">
                Menu, tabs, section and tree
              </Label>

              <HC
                direction={{ default: "column", md: "row" }}
                align="start"
                gap="lg"
              >
                <Menu
                  items={menuItems}
                  onSelect={(item) => alert(item.label)}
                />

                <VC flex={1} gap="md">
                  <Tabs>
                    <Tab
                      id="details"
                      label="Details"
                      icon="fa-solid fa-circle-info"
                    >
                      <p>Product details appear here.</p>
                    </Tab>
                    <Tab
                      id="history"
                      label="History"
                      icon="fa-solid fa-clock-rotate-left"
                    >
                      <p>Change history appears here.</p>
                    </Tab>
                  </Tabs>

                  <Section title="Advanced settings" defaultOpen>
                    <p>Accordion content can contain any React component.</p>
                  </Section>

                  <Tree
                    nodes={tree}
                    value={treeValue}
                    defaultExpanded
                    onSelect={(model) => setTreeValue(model.value)}
                  />
                </VC>
              </HC>
            </VC>
          </section>

          <section className="fui-demo-card">
            <VC gap="md">
              <Label fontSize="xl" fontWeight="bold">
                Sortable table
              </Label>
              <Table
                data={sorted}
                columns={columns}
                sort={sort}
                onSortChange={setSort}
              />
            </VC>
          </section>

          <section className="fui-demo-card">
            <VC gap="md">
              <Label fontSize="xl" fontWeight="bold">
                Dialog positions
              </Label>
              <HC wrap="wrap" gap="sm">
                {(
                  [
                    "center",
                    "left",
                    "top",
                    "bottom",
                    "right",
                  ] as DialogPosition[]
                ).map((position) => (
                  <Button
                    key={position}
                    variant="outline"
                    onClick={() => setDialog(position)}
                  >
                    {position}
                  </Button>
                ))}
              </HC>
            </VC>
          </section>

          <Dialog
            open={dialog !== null}
            position={dialog ?? "center"}
            header={
              <Label fontSize="lg" fontWeight="bold">
                {dialog} dialog
              </Label>
            }
            body={
              <VC gap="md">
                <p>
                  The header, body and footer are React components. The body
                  becomes scrollable when necessary.
                </p>
                <Input placeholder="Dialog input" />
              </VC>
            }
            footer={
              <HC justify="end" gap="sm" width="full">
                <Button variant="ghost" onClick={() => setDialog(null)}>
                  Cancel
                </Button>
                <Button onClick={() => setDialog(null)}>Confirm</Button>
              </HC>
            }
            onOpen={() => console.log("Dialog opened")}
            onClose={() => setDialog(null)}
          />
        </VC>
      </main>
    </FlowUIProvider>
  );
}

// examples/angular/src/app/app.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import {
  FlowBadgeComponent,
  FlowButtonComponent,
  FlowButtonGroupComponent,
  FlowCardComponent,
  FlowCheckboxComponent,
  FlowColorPickerComponent,
  FlowDialogComponent,
  FlowDividerComponent,
  FlowDropdownComponent,
  FlowHStackComponent,
  FlowIconComponent,
  FlowImageComponent,
  FlowInputComponent,
  FlowLabelComponent,
  FlowMenuComponent,
  FlowPasswordInputComponent,
  FlowRadioGroupComponent,
  FlowSectionComponent,
  FlowSliderComponent,
  FlowSwitchComponent,
  FlowTabComponent,
  FlowTableComponent,
  FlowTabsComponent,
  FlowTextAreaComponent,
  FlowTooltipComponent,
  FlowTreeComponent,
  FlowTreeDropdownComponent,
  FlowVStackComponent,
  type DialogPosition,
  type DropdownModel,
  type MenuItem,
  type SortState,
  type TableColumn,
  type TreeModel,
} from "@akin2unde/flowui-angular";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    CommonModule,
    FlowBadgeComponent,
    FlowButtonComponent,
    FlowButtonGroupComponent,
    FlowCardComponent,
    FlowCheckboxComponent,
    FlowColorPickerComponent,
    FlowDialogComponent,
    FlowDividerComponent,
    FlowDropdownComponent,
    FlowHStackComponent,
    FlowIconComponent,
    FlowImageComponent,
    FlowInputComponent,
    FlowLabelComponent,
    FlowMenuComponent,
    FlowPasswordInputComponent,
    FlowRadioGroupComponent,
    FlowSectionComponent,
    FlowSliderComponent,
    FlowSwitchComponent,
    FlowTabComponent,
    FlowTableComponent,
    FlowTabsComponent,
    FlowTextAreaComponent,
    FlowTooltipComponent,
    FlowTreeComponent,
    FlowTreeDropdownComponent,
    FlowVStackComponent,
  ],
  templateUrl: "./app.component.html",
})
export class AppComponent {
  name = "";
  password = "";
  notes = "";
  checked = true;
  notifications = true;
  volume = 40;
  status = "active";
  color = "#6d28d9";
  country: string | number = "ng";
  location: string | number = "lagos";
  treeValue: string | number = "lagos";
  dialog: DialogPosition | null = null;

  readonly menuItems: MenuItem[] = [
    {
      id: "new",
      label: "New product",
      icon: "fa-solid fa-plus",
    },
    {
      id: "messages",
      label: "Messages",
      icon: "fa-solid fa-envelope",
      badge: 4,
    },
    {
      id: "separator",
      label: "",
      separator: true,
    },
    {
      id: "delete",
      label: "Delete",
      icon: "fa-solid fa-trash",
    },
  ];

  readonly countries: DropdownModel[] = [
    {
      display: "Nigeria",
      value: "ng",
      other: { phoneCode: "+234" },
    },
    {
      display: "United Kingdom",
      value: "uk",
      other: { phoneCode: "+44" },
    },
  ];

  readonly tree: TreeModel[] = [
    {
      display: "Nigeria",
      value: "ng",
      other: { type: "country" },
      children: [
        {
          display: "Lagos",
          value: "lagos",
          other: { type: "state" },
        },
        {
          display: "Abuja",
          value: "abuja",
          other: { type: "city" },
        },
      ],
    },
    {
      display: "United Kingdom",
      value: "uk",
      other: { type: "country" },
      children: [
        {
          display: "London",
          value: "london",
          other: { type: "city" },
        },
      ],
    },
  ];

  data: Record<string, unknown>[] = [
    { name: "Rice", category: "Food", price: 42000 },
    { name: "Vegetable oil", category: "Food", price: 18500 },
    { name: "Detergent", category: "Home", price: 9300 },
  ];

  readonly columns: TableColumn<Record<string, unknown>>[] = [
    {
      field: "name",
      header: "Product",
      sortable: true,
    },
    {
      field: "category",
      header: "Category",
      sortable: true,
    },
    {
      field: "price",
      header: "Price",
      sortable: true,
      align: "right",
      format: (value) => `₦${Number(value).toLocaleString()}`,
    },
  ];

  sort: SortState = {
    field: "name",
    direction: "asc",
  };

  readonly positions: DialogPosition[] = [
    "center",
    "left",
    "top",
    "bottom",
    "right",
  ];

  selectCountry(model: DropdownModel): void {
    this.country = model.value;
  }

  selectLocation(model: TreeModel): void {
    this.location = model.value;
  }

  sortChanged(next: SortState): void {
    this.sort = next;
    this.data = [...this.data].sort((first, second) => {
      if (!next.direction) return 0;

      const result = String(first[next.field]).localeCompare(
        String(second[next.field]),
        undefined,
        { numeric: true },
      );

      return next.direction === "asc" ? result : -result;
    });
  }

  dialogOpened(): void {
    console.log("Dialog opened");
  }
}

<main class="fui-page">
  <fui-vc
    maxWidth="80rem"
    marginX="auto"
    [padding]="{ default: 'md', md: 'xl' }"
    gap="lg"
  >
    <fui-vc gap="xs">
      <fui-label fontSize="3xl" fontWeight="bold">
        FlowUI Angular Gallery
      </fui-label>
      <fui-label textColor="textMuted">
        Every FlowUI component in one working example.
      </fui-label>
    </fui-vc>

    <ng-template #cardHeader>
      <fui-label fontSize="xl" fontWeight="bold">
        Card, layout, label, icon, badge and image
      </fui-label>
    </ng-template>

    <ng-template #cardFooter>
      <fui-label textColor="textMuted">Reusable card footer</fui-label>
    </ng-template>

    <fui-card variant="elevated" [header]="cardHeader" [footer]="cardFooter">
      <fui-hc
        [direction]="{ default: 'column', md: 'row' }"
        align="center"
        gap="lg"
      >
        <fui-image
          src="https://picsum.photos/320/180"
          alt="Sample landscape"
          [width]="{ default: 'full', md: 320 }"
          [height]="180"
          cornerRadius="lg"
        />

        <fui-vc gap="sm" [flex]="1">
          <fui-hc gap="sm" align="center">
            <fui-icon icon="fa-solid fa-layer-group" textColor="primary.600" />
            <fui-label>Horizontal container</fui-label>
            <fui-badge icon="fa-solid fa-check">Ready</fui-badge>
          </fui-hc>

          <fui-label [lines]="1">
            This deliberately long label demonstrates single-line truncation
            when its available width becomes limited.
          </fui-label>

          <fui-divider label="or" />

          <fui-hc [height]="30" gap="md">
            <span>Left</span>
            <fui-divider orientation="vertical" />
            <span>Right</span>
          </fui-hc>
        </fui-vc>
      </fui-hc>
    </fui-card>

    <section class="fui-demo-card">
      <fui-vc gap="md">
        <fui-label fontSize="xl" fontWeight="bold">
          Buttons, groups and tooltips
        </fui-label>

        <fui-hc wrap="wrap" gap="sm">
          <fui-button icon="fa-solid fa-floppy-disk">Save</fui-button>
          <fui-button
            variant="outline"
            color="secondary"
            icon="fa-solid fa-arrow-right"
            iconPosition="right"
          >
            Continue
          </fui-button>
          <fui-button variant="soft" color="success" [badge]="3">
            Approved
          </fui-button>
          <fui-button
            variant="ghost"
            color="danger"
            icon="fa-solid fa-trash"
            iconPosition="center"
            ariaLabel="Delete"
          />
        </fui-hc>

        <fui-button-group>
          <fui-button>Day</fui-button>
          <fui-button variant="outline">Week</fui-button>
          <fui-button variant="outline">Month</fui-button>
        </fui-button-group>

        <fui-hc wrap="wrap" gap="lg">
          <fui-tooltip text="Shown on top" location="top">
            <fui-button variant="outline">top</fui-button>
          </fui-tooltip>
          <fui-tooltip text="Shown on right" location="right">
            <fui-button variant="outline">right</fui-button>
          </fui-tooltip>
          <fui-tooltip text="Shown at bottom" location="bottom">
            <fui-button variant="outline">bottom</fui-button>
          </fui-tooltip>
          <fui-tooltip text="Shown on left" location="left">
            <fui-button variant="outline">left</fui-button>
          </fui-tooltip>
        </fui-hc>
      </fui-vc>
    </section>

    <section class="fui-demo-card">
      <fui-vc gap="md">
        <fui-label fontSize="xl" fontWeight="bold"> Form controls </fui-label>

        <fui-label htmlFor="product-name" [required]="true">
          Product name
        </fui-label>
        <fui-input
          id="product-name"
          [value]="name"
          placeholder="Enter product name"
          (valueChange)="name = $event"
        />
        <fui-password-input
          [value]="password"
          placeholder="Enter password"
          (valueChange)="password = $event"
        />
        <fui-textarea
          [value]="notes"
          placeholder="Notes"
          (valueChange)="notes = $event"
        />

        <fui-hc wrap="wrap" gap="lg">
          <fui-checkbox
            label="Available for sale"
            [checked]="checked"
            (checkedChange)="checked = $event"
          />
          <fui-switch
            label="Enable notifications"
            [checked]="notifications"
            (checkedChange)="notifications = $event"
          />
          <fui-color-picker [value]="color" (valueChange)="color = $event" />
        </fui-hc>

        <fui-radio-group
          name="status"
          [value]="status"
          orientation="horizontal"
          [options]="[
            { label: 'Active', value: 'active' },
            { label: 'Inactive', value: 'inactive' },
          ]"
          (valueChange)="status = $event"
        />

        <fui-slider [value]="volume" (valueChange)="volume = $event" />

        <fui-dropdown
          [value]="country"
          [options]="countries"
          (selected)="selectCountry($event)"
        />

        <fui-tree-dropdown
          [value]="location"
          [options]="tree"
          (selected)="selectLocation($event)"
        />
      </fui-vc>
    </section>

    <section class="fui-demo-card">
      <fui-vc gap="md">
        <fui-label fontSize="xl" fontWeight="bold">
          Menu, tabs, section and tree
        </fui-label>

        <fui-hc
          [direction]="{ default: 'column', md: 'row' }"
          align="start"
          gap="lg"
        >
          <fui-menu [items]="menuItems" (selected)="name = $event.label" />

          <fui-vc [flex]="1" gap="md">
            <fui-tabs>
              <fui-tab
                id="details"
                label="Details"
                icon="fa-solid fa-circle-info"
              >
                <p>Product details appear here.</p>
              </fui-tab>
              <fui-tab
                id="history"
                label="History"
                icon="fa-solid fa-clock-rotate-left"
              >
                <p>Change history appears here.</p>
              </fui-tab>
            </fui-tabs>

            <fui-section title="Advanced settings" [defaultOpen]="true">
              <p>Accordion content can contain any Angular component.</p>
            </fui-section>

            <fui-tree
              [nodes]="tree"
              [value]="treeValue"
              [defaultExpanded]="true"
              (selected)="treeValue = $event.value"
            />
          </fui-vc>
        </fui-hc>
      </fui-vc>
    </section>

    <section class="fui-demo-card">
      <fui-vc gap="md">
        <fui-label fontSize="xl" fontWeight="bold"> Sortable table </fui-label>
        <fui-table
          [data]="data"
          [columns]="columns"
          [sort]="sort"
          (sortChange)="sortChanged($event)"
        />
      </fui-vc>
    </section>

    <section class="fui-demo-card">
      <fui-vc gap="md">
        <fui-label fontSize="xl" fontWeight="bold">
          Dialog positions
        </fui-label>
        <fui-hc wrap="wrap" gap="sm">
          <fui-button
            *ngFor="let position of positions"
            variant="outline"
            (pressed)="dialog = position"
          >
            {{ position }}
          </fui-button>
        </fui-hc>
      </fui-vc>
    </section>

    <ng-template #dialogHeader>
      <fui-label fontSize="lg" fontWeight="bold">
        {{ dialog }} dialog
      </fui-label>
    </ng-template>

    <ng-template #dialogBody>
      <fui-vc gap="md">
        <p>
          The header, body and footer are Angular templates containing
          components.
        </p>
        <fui-input placeholder="Dialog input" />
      </fui-vc>
    </ng-template>

    <ng-template #dialogFooter>
      <fui-hc justify="end" gap="sm" width="full">
        <fui-button variant="ghost" (pressed)="dialog = null">
          Cancel
        </fui-button>
        <fui-button (pressed)="dialog = null">Confirm</fui-button>
      </fui-hc>
    </ng-template>

    <fui-dialog
      [open]="dialog !== null"
      [position]="dialog ?? 'center'"
      [header]="dialogHeader"
      [body]="dialogBody"
      [footer]="dialogFooter"
      (opened)="dialogOpened()"
      (closed)="dialog = null"
    />
  </fui-vc>
</main>
