// packages/angular/src/lib/dialog.ts
import { CommonModule } from "@angular/common";
import {
  Component,
  EventEmitter,
  HostListener,
  Input,
  Output,
  TemplateRef,
} from "@angular/core";
import type { DialogPosition } from "@akin2unde/flowui-core";
import { FlowComponentBase } from "./base";
import { FlowButtonComponent } from "./actions";

@Component({
  selector: "fui-dialog",
  standalone: true,
  imports: [CommonModule, FlowButtonComponent],
  template: `<div
    *ngIf="open"
    class="fui-dialog-overlay"
    (mousedown)="overlayClick($event)"
  >
    <section
      [class]="view().className"
      [ngStyle]="view().style"
      [attr.data-position]="position"
      role="dialog"
      aria-modal="true"
    >
      <header *ngIf="header || showCloseButton" class="fui-dialog-header">
        <ng-container *ngIf="header" [ngTemplateOutlet]="header" /><fui-button
          *ngIf="showCloseButton"
          variant="ghost"
          icon="fa-solid fa-xmark"
          iconPosition="center"
          ariaLabel="Close dialog"
          (pressed)="close()"
        />
      </header>
      <div
        [class]="
          'fui-dialog-body' + (scrollableBody ? ' fui-dialog-body-scroll' : '')
        "
      >
        <ng-container *ngIf="body" [ngTemplateOutlet]="body" /><ng-content />
      </div>
      <footer *ngIf="footer" class="fui-dialog-footer">
        <ng-container [ngTemplateOutlet]="footer" />
      </footer>
    </section>
  </div>`,
})
export class FlowDialogComponent extends FlowComponentBase {
  private currentOpen = false;
  @Input() set open(value: boolean) {
    if (value && !this.currentOpen) this.opened.emit();
    this.currentOpen = value;
  }
  get open() {
    return this.currentOpen;
  }
  @Input() position: DialogPosition = "center";
  @Input() header?: TemplateRef<unknown>;
  @Input() body?: TemplateRef<unknown>;
  @Input() footer?: TemplateRef<unknown>;
  @Input() scrollableBody = true;
  @Input() closeOnOverlayClick = true;
  @Input() closeOnEscape = true;
  @Input() showCloseButton = true;
  @Output() openChange = new EventEmitter<boolean>();
  @Output() opened = new EventEmitter<void>();
  @Output() closed = new EventEmitter<void>();
  @HostListener("document:keydown.escape") escape() {
    if (this.open && this.closeOnEscape) this.close();
  }
  overlayClick(event: MouseEvent) {
    if (this.closeOnOverlayClick && event.target === event.currentTarget)
      this.close();
  }
  close() {
    this.open = false;
    this.openChange.emit(false);
    this.closed.emit();
  }
  view = () => this.resolved("fui-dialog");
}

// packages/react/src/dialog.tsx
import { useEffect, useRef, type ReactNode } from "react";
import { createPortal } from "react-dom";
import type { BaseUIProps, DialogPosition } from "@akin2unde/flowui-core";
import { useFlowProps } from "./helpers";
import { Button } from "./actions";

export interface DialogProps extends BaseUIProps {
  open: boolean;
  position?: DialogPosition;
  header?: ReactNode;
  body?: ReactNode;
  footer?: ReactNode;
  scrollableBody?: boolean;
  closeOnOverlayClick?: boolean;
  closeOnEscape?: boolean;
  showCloseButton?: boolean;
  onOpen?: () => void;
  onClose: () => void;
}
export function Dialog({
  open,
  position = "center",
  header,
  body,
  footer,
  scrollableBody = true,
  closeOnOverlayClick = true,
  closeOnEscape = true,
  showCloseButton = true,
  onOpen,
  onClose,
  ...props
}: DialogProps) {
  const flow = useFlowProps("fui-dialog", props);
  const onOpenRef = useRef(onOpen);
  const onCloseRef = useRef(onClose);
  onOpenRef.current = onOpen;
  onCloseRef.current = onClose;
  useEffect(() => {
    if (!open) return;
    onOpenRef.current?.();
    const handler = (event: KeyboardEvent) => {
      if (closeOnEscape && event.key === "Escape") onCloseRef.current();
    };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [open, closeOnEscape]);
  if (!open) return null;
  return createPortal(
    <div
      className="fui-dialog-overlay"
      onMouseDown={(event) => {
        if (closeOnOverlayClick && event.target === event.currentTarget)
          onClose();
      }}
    >
      <section
        {...flow}
        data-position={position}
        role="dialog"
        aria-modal="true"
      >
        <header className="fui-dialog-header">
          <div>{header}</div>
          {showCloseButton && (
            <Button
              variant="ghost"
              icon="fa-solid fa-xmark"
              iconPosition="center"
              ariaLabel="Close dialog"
              onClick={onClose}
            />
          )}
        </header>
        <div
          className={`fui-dialog-body${scrollableBody ? " fui-dialog-body-scroll" : ""}`}
        >
          {body}
        </div>
        {footer && <footer className="fui-dialog-footer">{footer}</footer>}
      </section>
    </div>,
    document.body,
  );
}
