// packages/angular/src/lib/extras.ts
import { CommonModule } from "@angular/common";
import {
  Component,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
} from "@angular/core";
import type { TooltipLocation, TreeModel } from "@akin2unde/flowui-core";
import { FlowComponentBase } from "./base";
import { FlowIconComponent } from "./primitives";

@Component({
  selector: "fui-card",
  standalone: true,
  imports: [CommonModule],
  template: `
    <article
      [class]="view().className"
      [ngStyle]="view().style"
      [attr.data-variant]="variant"
    >
      <header *ngIf="header" class="fui-card-header">
        <ng-container [ngTemplateOutlet]="header" />
      </header>

      <div class="fui-card-body">
        <ng-content />
      </div>

      <footer *ngIf="footer" class="fui-card-footer">
        <ng-container [ngTemplateOutlet]="footer" />
      </footer>
    </article>
  `,
})
export class FlowCardComponent extends FlowComponentBase {
  @Input() header?: TemplateRef<unknown>;
  @Input() footer?: TemplateRef<unknown>;
  @Input() variant: "outline" | "elevated" | "filled" = "outline";

  view = () => this.resolved("fui-card");
}

@Component({
  selector: "fui-slider",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <input
        class="fui-slider"
        type="range"
        [min]="min"
        [max]="max"
        [step]="step"
        [value]="value"
        [name]="name ?? ''"
        [disabled]="disabled"
        (input)="valueChange.emit(+$any($event.target).value)"
      />
      <output *ngIf="showValue" class="fui-slider-value">
        {{ value }}
      </output>
    </div>
  `,
})
export class FlowSliderComponent extends FlowComponentBase {
  @Input() min = 0;
  @Input() max = 100;
  @Input() step = 1;
  @Input() value = 0;
  @Input() name?: string;
  @Input() disabled = false;
  @Input() showValue = true;

  @Output() valueChange = new EventEmitter<number>();

  view = () => this.resolved("fui-slider-wrap");
}

@Component({
  selector: "fui-switch",
  standalone: true,
  imports: [CommonModule],
  template: `
    <label [class]="view().className" [ngStyle]="view().style">
      <input
        class="fui-switch-input"
        type="checkbox"
        role="switch"
        [checked]="checked"
        [name]="name ?? ''"
        [disabled]="disabled"
        (change)="checkedChange.emit($any($event.target).checked)"
      />
      <span class="fui-switch-track" aria-hidden="true">
        <span class="fui-switch-thumb"></span>
      </span>
      <span *ngIf="label">{{ label }}</span>
    </label>
  `,
})
export class FlowSwitchComponent extends FlowComponentBase {
  @Input() checked = false;
  @Input() label?: string;
  @Input() name?: string;
  @Input() disabled = false;

  @Output() checkedChange = new EventEmitter<boolean>();

  view = () => this.resolved("fui-switch-label");
}

interface VisibleTreeNode {
  node: TreeModel;
  depth: number;
  hasChildren: boolean;
  expanded: boolean;
}

@Component({
  selector: "fui-tree",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <ul [class]="view().className" [ngStyle]="view().style" role="tree">
      <li
        *ngFor="let item of visibleNodes"
        class="fui-tree-item"
        role="treeitem"
        [attr.aria-expanded]="item.hasChildren ? item.expanded : null"
      >
        <div
          class="fui-tree-row"
          [class.fui-tree-row-selected]="value === item.node.value"
          [style.padding-left.rem]="item.depth"
        >
          <button
            class="fui-tree-toggle"
            type="button"
            [disabled]="!item.hasChildren"
            [attr.aria-label]="item.expanded ? 'Collapse' : 'Expand'"
            (click)="toggle(item.node.value)"
          >
            <fui-icon
              *ngIf="item.hasChildren"
              [icon]="
                'fa-solid fa-chevron-' + (item.expanded ? 'down' : 'right')
              "
            />
          </button>

          <button
            class="fui-tree-select"
            type="button"
            (click)="selected.emit(item.node)"
          >
            {{ item.node.display }}
          </button>
        </div>
      </li>
    </ul>
  `,
})
export class FlowTreeComponent extends FlowComponentBase {
  @Input() nodes: TreeModel[] = [];
  @Input() value?: string | number;
  @Input() defaultExpanded = false;

  @Output() selected = new EventEmitter<TreeModel>();

  private readonly expanded = new Set<string | number>();
  private initialized = false;

  get visibleNodes(): VisibleTreeNode[] {
    if (!this.initialized && this.defaultExpanded) {
      for (const node of this.nodes) {
        this.expanded.add(node.value);
      }
      this.initialized = true;
    }

    const result: VisibleTreeNode[] = [];

    const visit = (nodes: TreeModel[], depth: number): void => {
      for (const node of nodes) {
        const hasChildren = Boolean(node.children?.length);
        const isExpanded = this.expanded.has(node.value);

        result.push({
          node,
          depth,
          hasChildren,
          expanded: isExpanded,
        });

        if (hasChildren && isExpanded) {
          visit(node.children ?? [], depth + 1);
        }
      }
    };

    visit(this.nodes, 0);
    return result;
  }

  toggle(value: string | number): void {
    if (this.expanded.has(value)) {
      this.expanded.delete(value);
    } else {
      this.expanded.add(value);
    }
  }

  view = () => this.resolved("fui-tree fui-tree-view");
}

@Component({
  selector: "fui-tooltip",
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      [class]="view().className"
      [ngStyle]="view().style"
      [attr.data-location]="location"
    >
      <ng-content />
      <span class="fui-tooltip-content" role="tooltip">
        {{ text }}
      </span>
    </span>
  `,
})
export class FlowTooltipComponent extends FlowComponentBase {
  @Input({ required: true }) text!: string;
  @Input() location: TooltipLocation = "top";
  @Input() delay = 150;

  view = () => {
    const resolved = this.resolved("fui-tooltip");
    resolved.style["--fui-tooltip-delay"] = `${this.delay}ms`;
    return resolved;
  };
}

// packages/react/src/extras.tsx
import {
  useState,
  type CSSProperties,
  type ChangeEventHandler,
  type PropsWithChildren,
  type ReactNode,
} from "react";
import type {
  CardProps as CoreCardProps,
  SliderProps as CoreSliderProps,
  SwitchProps as CoreSwitchProps,
  TooltipProps as CoreTooltipProps,
  TreeModel,
  TreeProps as CoreTreeProps,
} from "@akin2unde/flowui-core";
import { useFlowProps } from "./helpers";
import { Icon } from "./primitives";

export interface CardProps extends PropsWithChildren<CoreCardProps> {
  header?: ReactNode;
  footer?: ReactNode;
}

export function Card({
  children,
  header,
  footer,
  variant = "outline",
  ...props
}: CardProps) {
  const flow = useFlowProps("fui-card", props);

  return (
    <article {...flow} data-variant={variant}>
      {header && <header className="fui-card-header">{header}</header>}
      <div className="fui-card-body">{children}</div>
      {footer && <footer className="fui-card-footer">{footer}</footer>}
    </article>
  );
}

export interface SliderProps extends CoreSliderProps {
  onChange?: (value: number) => void;
  showValue?: boolean;
}

export function Slider({
  min = 0,
  max = 100,
  step = 1,
  value = 0,
  name,
  disabled,
  onChange,
  showValue = true,
  ...props
}: SliderProps) {
  const flow = useFlowProps("fui-slider-wrap", props);

  return (
    <div {...flow}>
      <input
        className="fui-slider"
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        name={name}
        disabled={disabled}
        onChange={(event) => onChange?.(Number(event.target.value))}
      />
      {showValue && <output className="fui-slider-value">{value}</output>}
    </div>
  );
}

export interface SwitchProps extends CoreSwitchProps {
  onChange?: (checked: boolean) => void;
}

export function Switch({
  checked = false,
  label,
  name,
  disabled,
  onChange,
  ...props
}: SwitchProps) {
  const flow = useFlowProps("fui-switch-label", props);

  return (
    <label {...flow}>
      <input
        className="fui-switch-input"
        type="checkbox"
        role="switch"
        checked={checked}
        name={name}
        disabled={disabled}
        onChange={(event) => onChange?.(event.target.checked)}
      />
      <span className="fui-switch-track" aria-hidden="true">
        <span className="fui-switch-thumb" />
      </span>
      {label && <span>{label}</span>}
    </label>
  );
}

interface TreeNodeProps {
  node: TreeModel;
  value?: string | number;
  expanded: Set<string | number>;
  onToggle: (value: string | number) => void;
  onSelect?: (node: TreeModel) => void;
}

function TreeNode({
  node,
  value,
  expanded,
  onToggle,
  onSelect,
}: TreeNodeProps) {
  const hasChildren = Boolean(node.children?.length);
  const isExpanded = expanded.has(node.value);

  return (
    <li
      className="fui-tree-item"
      role="treeitem"
      aria-expanded={hasChildren ? isExpanded : undefined}
    >
      <div
        className={`fui-tree-row${value === node.value ? " fui-tree-row-selected" : ""}`}
      >
        <button
          className="fui-tree-toggle"
          type="button"
          aria-label={isExpanded ? "Collapse" : "Expand"}
          disabled={!hasChildren}
          onClick={() => hasChildren && onToggle(node.value)}
        >
          {hasChildren && (
            <Icon
              icon={`fa-solid fa-chevron-${isExpanded ? "down" : "right"}`}
            />
          )}
        </button>
        <button
          className="fui-tree-select"
          type="button"
          onClick={() => onSelect?.(node)}
        >
          {node.display}
        </button>
      </div>
      {hasChildren && isExpanded && (
        <ul className="fui-tree-children" role="group">
          {node.children?.map((child) => (
            <TreeNode
              key={child.value}
              node={child}
              value={value}
              expanded={expanded}
              onToggle={onToggle}
              onSelect={onSelect}
            />
          ))}
        </ul>
      )}
    </li>
  );
}

export interface TreeProps extends Omit<CoreTreeProps, "nodes"> {
  nodes: TreeModel[];
  onSelect?: (node: TreeModel) => void;
}

export function Tree({
  nodes,
  value,
  defaultExpanded = false,
  onSelect,
  ...props
}: TreeProps) {
  const initialValues = defaultExpanded ? nodes.map((node) => node.value) : [];
  const [expanded, setExpanded] = useState<Set<string | number>>(
    new Set(initialValues),
  );
  const flow = useFlowProps("fui-tree fui-tree-view", props);

  const toggle = (nodeValue: string | number) => {
    setExpanded((current) => {
      const next = new Set(current);
      if (next.has(nodeValue)) next.delete(nodeValue);
      else next.add(nodeValue);
      return next;
    });
  };

  return (
    <ul {...flow} role="tree">
      {nodes.map((node) => (
        <TreeNode
          key={node.value}
          node={node}
          value={value}
          expanded={expanded}
          onToggle={toggle}
          onSelect={onSelect}
        />
      ))}
    </ul>
  );
}

export interface TooltipProps extends PropsWithChildren<CoreTooltipProps> {}

export function Tooltip({
  children,
  text,
  location = "top",
  delay = 150,
  ...props
}: TooltipProps) {
  const flow = useFlowProps("fui-tooltip", props);
  const tooltipStyle = {
    ...flow.style,
    "--fui-tooltip-delay": `${delay}ms`,
  } as CSSProperties;

  return (
    <span {...flow} style={tooltipStyle} data-location={location}>
      {children}
      <span className="fui-tooltip-content" role="tooltip">
        {text}
      </span>
    </span>
  );
}
