// packages/angular/src/lib/selection.ts
import { CommonModule } from "@angular/common";
import {
  Component,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
} from "@angular/core";
import {
  enabledSelectableDescendants,
  filterTree,
  flattenTree,
  resolveColorValue,
  selectedTreeModels,
  type ColorValue,
  type DropdownModel,
  type TreeModel,
} from "@akin2unde/flowui-core";
import { FlowComponentBase } from "./base";
import { FlowIconComponent } from "./primitives";

@Component({
  selector: "fui-multi-select",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <div
        class="fui-multi-select-trigger"
        role="combobox"
        [attr.aria-expanded]="open"
        [tabIndex]="disabled ? -1 : 0"
        (click)="toggleOpen()"
        (keydown.enter)="toggleOpen()"
        (keydown.space)="$event.preventDefault(); toggleOpen()"
      >
        <span class="fui-chip-list">
          <ng-container *ngIf="visibleChips.length; else placeholderContent">
            <span
              *ngFor="let option of visibleChips"
              class="fui-select-chip"
              [ngStyle]="chipStyle"
            >
              <ng-container
                *ngIf="chipTemplate; else plainChip"
                [ngTemplateOutlet]="chipTemplate"
                [ngTemplateOutletContext]="{ $implicit: option }"
              />
              <ng-template #plainChip>{{ option.display }}</ng-template>
              <button
                class="fui-select-chip-close"
                type="button"
                [ngStyle]="closeStyle"
                [disabled]="disabled"
                [attr.aria-label]="'Remove ' + option.display"
                (keydown)="$event.stopPropagation()"
                (click)="remove(option); $event.stopPropagation()"
              >
                <fui-icon icon="fa-solid fa-xmark" />
              </button>
            </span>
          </ng-container>
          <ng-template #placeholderContent>
            <span class="fui-select-placeholder">{{ placeholder }}</span>
          </ng-template>
          <span
            *ngIf="selectedOptions.length > maxVisibleChips"
            class="fui-select-chip-overflow"
          >
            +{{ selectedOptions.length - maxVisibleChips }}
          </span>
        </span>
        <button
          class="fui-multi-select-toggle"
          type="button"
          [disabled]="disabled"
          [attr.aria-expanded]="open"
          aria-label="Toggle options"
          (keydown)="$event.stopPropagation()"
          (click)="$event.stopPropagation(); toggleOpen()"
        >
          <fui-icon [icon]="'fa-solid fa-chevron-' + (open ? 'up' : 'down')" />
        </button>
      </div>

      <div *ngIf="open" class="fui-select-menu">
        <label *ngIf="searchable" class="fui-select-search">
          <fui-icon icon="fa-solid fa-magnifying-glass" />
          <input
            [value]="query"
            [placeholder]="searchPlaceholder"
            (input)="search($any($event.target).value)"
          />
        </label>
        <div
          class="fui-select-options"
          role="listbox"
          aria-multiselectable="true"
        >
          <ng-container *ngIf="matches.length; else empty">
            <ng-container *ngFor="let group of groups">
              <div *ngIf="grouped" class="fui-select-group">{{ group }}</div>
              <button
                *ngFor="let option of optionsForGroup(group)"
                class="fui-select-option"
                type="button"
                role="option"
                [disabled]="option.disabled"
                [attr.aria-selected]="isSelected(option)"
                (click)="toggle(option)"
              >
                <input
                  *ngIf="showCheckboxes"
                  type="checkbox"
                  [checked]="isSelected(option)"
                  tabindex="-1"
                  readonly
                />
                <span>
                  <ng-container
                    *ngIf="optionTemplate; else plainOption"
                    [ngTemplateOutlet]="optionTemplate"
                    [ngTemplateOutletContext]="{
                      $implicit: option,
                      selected: isSelected(option),
                    }"
                  />
                  <ng-template #plainOption>{{ option.display }}</ng-template>
                </span>
              </button>
            </ng-container>
          </ng-container>
          <ng-template #empty
            ><div class="fui-select-empty">{{ emptyText }}</div></ng-template
          >
        </div>
        <button
          *ngIf="hasMore || loading"
          class="fui-select-load-more"
          type="button"
          [disabled]="loading"
          (click)="loadMore.emit()"
        >
          {{ loading ? "Loading…" : loadMoreText }}
        </button>
      </div>
    </div>
  `,
})
export class FlowMultiSelectComponent extends FlowComponentBase {
  @Input() options: DropdownModel[] = [];
  @Input() value: Array<string | number> = [];
  @Input() searchable = false;
  @Input() grouped = false;
  @Input() searchPlaceholder = "Search…";
  @Input() placeholder = "Select options";
  @Input() emptyText = "No options found";
  @Input() disabled = false;
  @Input() loading = false;
  @Input() hasMore = false;
  @Input() loadMoreText = "Load more";
  @Input() maxVisibleChips = 3;
  @Input() showCheckboxes = true;
  @Input() chipTextColor?: ColorValue;
  @Input() chipBackgroundColor?: ColorValue;
  @Input() chipCloseIconColor?: ColorValue;
  @Input() optionTemplate?: TemplateRef<{
    $implicit: DropdownModel;
    selected: boolean;
  }>;
  @Input() chipTemplate?: TemplateRef<{ $implicit: DropdownModel }>;

  @Output() valueChange = new EventEmitter<Array<string | number>>();
  @Output() selectedChange = new EventEmitter<DropdownModel[]>();
  @Output() searchChange = new EventEmitter<string>();
  @Output() loadMore = new EventEmitter<void>();

  open = false;
  query = "";

  get selectedOptions(): DropdownModel[] {
    return this.options.filter((option) => this.value.includes(option.value));
  }

  get visibleChips(): DropdownModel[] {
    return this.selectedOptions.slice(0, this.maxVisibleChips);
  }

  get matches(): DropdownModel[] {
    return this.options.filter((option) =>
      String(option.display).toLowerCase().includes(this.query.toLowerCase()),
    );
  }

  get groups(): Array<string | number | undefined> {
    return this.grouped
      ? Array.from(
          new Set(this.matches.map((option) => option.group ?? "Other")),
        )
      : [undefined];
  }

  get chipStyle(): Record<string, string | undefined> {
    return {
      color: this.chipTextColor
        ? resolveColorValue(this.chipTextColor)
        : undefined,
      backgroundColor: this.chipBackgroundColor
        ? resolveColorValue(this.chipBackgroundColor)
        : undefined,
    };
  }

  get closeStyle(): Record<string, string | undefined> {
    return {
      color: this.chipCloseIconColor
        ? resolveColorValue(this.chipCloseIconColor)
        : undefined,
    };
  }

  optionsForGroup(group: string | number | undefined): DropdownModel[] {
    return this.matches.filter(
      (option) => !this.grouped || (option.group ?? "Other") === group,
    );
  }

  isSelected(option: DropdownModel): boolean {
    return this.value.includes(option.value);
  }

  search(query: string): void {
    this.query = query;
    this.searchChange.emit(query);
  }

  toggleOpen(): void {
    if (!this.disabled) this.open = !this.open;
  }

  toggle(option: DropdownModel): void {
    if (option.disabled) return;
    this.emit(
      this.isSelected(option)
        ? this.value.filter((item) => item !== option.value)
        : [...this.value, option.value],
    );
  }

  remove(option: DropdownModel): void {
    this.emit(this.value.filter((item) => item !== option.value));
  }

  private emit(values: Array<string | number>): void {
    this.value = values;
    this.valueChange.emit(values);
    this.selectedChange.emit(
      this.options.filter((option) => values.includes(option.value)),
    );
  }

  view = () => this.resolved("fui-multi-select");
}

interface FlatTreeNode extends TreeModel {
  depth: number;
}

@Component({
  selector: "fui-tree-multi-select",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <div
        class="fui-multi-select-trigger"
        role="combobox"
        [attr.aria-expanded]="open"
        [tabIndex]="disabled ? -1 : 0"
        (click)="toggleOpen()"
        (keydown.enter)="toggleOpen()"
        (keydown.space)="$event.preventDefault(); toggleOpen()"
      >
        <span class="fui-chip-list">
          <ng-container *ngIf="visibleChips.length; else treePlaceholder">
            <span
              *ngFor="let node of visibleChips"
              class="fui-select-chip"
              [ngStyle]="chipStyle"
            >
              <ng-container
                *ngIf="chipTemplate; else plainTreeChip"
                [ngTemplateOutlet]="chipTemplate"
                [ngTemplateOutletContext]="{ $implicit: node }"
              />
              <ng-template #plainTreeChip>{{ node.display }}</ng-template>
              <button
                class="fui-select-chip-close"
                type="button"
                [ngStyle]="closeStyle"
                [attr.aria-label]="'Remove ' + node.display"
                (keydown)="$event.stopPropagation()"
                (click)="remove(node); $event.stopPropagation()"
              >
                <fui-icon icon="fa-solid fa-xmark" />
              </button>
            </span>
          </ng-container>
          <ng-template #treePlaceholder
            ><span class="fui-select-placeholder">{{
              placeholder
            }}</span></ng-template
          >
          <span
            *ngIf="selectedNodes.length > maxVisibleChips"
            class="fui-select-chip-overflow"
            >+{{ selectedNodes.length - maxVisibleChips }}</span
          >
        </span>
        <button
          class="fui-multi-select-toggle"
          type="button"
          [disabled]="disabled"
          [attr.aria-expanded]="open"
          aria-label="Toggle tree"
          (keydown)="$event.stopPropagation()"
          (click)="$event.stopPropagation(); toggleOpen()"
        >
          <fui-icon [icon]="'fa-solid fa-chevron-' + (open ? 'up' : 'down')" />
        </button>
      </div>
      <div *ngIf="open" class="fui-select-menu">
        <label *ngIf="searchable" class="fui-select-search">
          <fui-icon icon="fa-solid fa-magnifying-glass" />
          <input
            [value]="query"
            [placeholder]="searchPlaceholder"
            (input)="search($any($event.target).value)"
          />
        </label>
        <div class="fui-tree-multi" role="tree">
          <ng-container *ngIf="visibleNodes.length; else emptyTree">
            <div
              *ngFor="let node of visibleNodes"
              class="fui-tree-multi-row"
              [style.padding-left.rem]="node.depth * 1.25"
            >
              <button
                class="fui-tree-multi-toggle"
                type="button"
                [disabled]="!hasChildren(node)"
                (click)="toggleExpanded(node)"
              >
                <fui-icon
                  *ngIf="hasChildren(node)"
                  [icon]="
                    'fa-solid fa-chevron-' +
                    (isExpanded(node) ? 'down' : 'right')
                  "
                />
              </button>
              <input
                *ngIf="node.selectable !== false"
                type="checkbox"
                [checked]="isSelected(node)"
                [indeterminate]="isIndeterminate(node)"
                [disabled]="node.disabled"
                (change)="toggle(node)"
              />
              <button
                class="fui-tree-multi-label"
                type="button"
                [disabled]="node.disabled"
                (click)="
                  node.selectable === false
                    ? toggleExpanded(node)
                    : toggle(node)
                "
              >
                <ng-container
                  *ngIf="nodeTemplate; else plainNode"
                  [ngTemplateOutlet]="nodeTemplate"
                  [ngTemplateOutletContext]="{
                    $implicit: node,
                    selected: isSelected(node),
                  }"
                />
                <ng-template #plainNode>{{ node.display }}</ng-template>
              </button>
            </div>
          </ng-container>
          <ng-template #emptyTree
            ><div class="fui-select-empty">{{ emptyText }}</div></ng-template
          >
        </div>
      </div>
    </div>
  `,
})
export class FlowTreeMultiSelectComponent extends FlowComponentBase {
  @Input() nodes: TreeModel[] = [];
  @Input() value: Array<string | number> = [];
  @Input() expandedValues: Array<string | number> = [];
  @Input() searchable = false;
  @Input() searchPlaceholder = "Search tree…";
  @Input() placeholder = "Select from tree";
  @Input() emptyText = "No nodes found";
  @Input() disabled = false;
  @Input() cascadeSelection = true;
  @Input() maxVisibleChips = 3;
  @Input() chipTextColor?: ColorValue;
  @Input() chipBackgroundColor?: ColorValue;
  @Input() chipCloseIconColor?: ColorValue;
  @Input() nodeTemplate?: TemplateRef<{
    $implicit: TreeModel;
    selected: boolean;
  }>;
  @Input() chipTemplate?: TemplateRef<{ $implicit: TreeModel }>;

  @Output() valueChange = new EventEmitter<Array<string | number>>();
  @Output() selectedChange = new EventEmitter<TreeModel[]>();
  @Output() expandedValuesChange = new EventEmitter<Array<string | number>>();
  @Output() searchChange = new EventEmitter<string>();
  @Output() loadChildren = new EventEmitter<TreeModel>();

  open = false;
  query = "";

  get selectedNodes(): TreeModel[] {
    return selectedTreeModels(this.nodes, this.value);
  }

  get visibleChips(): TreeModel[] {
    return this.selectedNodes.slice(0, this.maxVisibleChips);
  }

  get chipStyle(): Record<string, string | undefined> {
    return {
      color: this.chipTextColor
        ? resolveColorValue(this.chipTextColor)
        : undefined,
      backgroundColor: this.chipBackgroundColor
        ? resolveColorValue(this.chipBackgroundColor)
        : undefined,
    };
  }

  get closeStyle(): Record<string, string | undefined> {
    return {
      color: this.chipCloseIconColor
        ? resolveColorValue(this.chipCloseIconColor)
        : undefined,
    };
  }

  get visibleNodes(): FlatTreeNode[] {
    const roots = filterTree(this.nodes, this.query);
    const result: FlatTreeNode[] = [];
    const visit = (nodes: TreeModel[], depth: number): void => {
      nodes.forEach((node) => {
        result.push({ ...node, depth });
        if (this.query || this.isExpanded(node))
          visit(node.children ?? [], depth + 1);
      });
    };
    visit(roots, 0);
    return result;
  }

  hasChildren(node: TreeModel): boolean {
    return Boolean(node.children?.length || node.hasChildren);
  }

  isExpanded(node: TreeModel): boolean {
    return this.expandedValues.includes(node.value);
  }

  isSelected(node: TreeModel): boolean {
    if (!this.cascadeSelection) return this.value.includes(node.value);
    const descendants = enabledSelectableDescendants(node);
    return (
      Boolean(descendants.length) &&
      descendants.every((item) => this.value.includes(item.value))
    );
  }

  isIndeterminate(node: TreeModel): boolean {
    if (!this.cascadeSelection) return false;
    const descendants = enabledSelectableDescendants(node);
    const count = descendants.filter((item) =>
      this.value.includes(item.value),
    ).length;
    return count > 0 && count < descendants.length;
  }

  search(query: string): void {
    this.query = query;
    this.searchChange.emit(query);
  }

  toggleOpen(): void {
    if (!this.disabled) this.open = !this.open;
  }

  toggle(node: TreeModel): void {
    if (node.disabled || node.selectable === false) return;
    const targets = this.cascadeSelection
      ? enabledSelectableDescendants(node).map((item) => item.value)
      : [node.value];
    const remove = targets.every((target) => this.value.includes(target));
    this.emit(
      remove
        ? this.value.filter((item) => !targets.includes(item))
        : Array.from(new Set([...this.value, ...targets])),
    );
  }

  remove(node: TreeModel): void {
    this.emit(this.value.filter((item) => item !== node.value));
  }

  toggleExpanded(node: TreeModel): void {
    const next = this.isExpanded(node)
      ? this.expandedValues.filter((item) => item !== node.value)
      : [...this.expandedValues, node.value];
    this.expandedValues = next;
    this.expandedValuesChange.emit(next);
    if (!node.children?.length && node.hasChildren)
      this.loadChildren.emit(node);
  }

  private emit(values: Array<string | number>): void {
    this.value = values;
    this.valueChange.emit(values);
    this.selectedChange.emit(selectedTreeModels(this.nodes, values));
  }

  view = () => this.resolved("fui-tree-multi-select");
}

// packages/react/src/selection.tsx
import {
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import {
  enabledSelectableDescendants,
  filterTree,
  flattenTree,
  resolveColorValue,
  selectedTreeModels,
  type DropdownModel,
  type MultiSelectProps as CoreMultiSelectProps,
  type TreeModel,
  type TreeMultiSelectProps as CoreTreeMultiSelectProps,
} from "@akin2unde/flowui-core";
import { useFlowProps } from "./helpers";
import { Icon } from "./primitives";

interface ChipColors {
  chipTextColor?: CoreMultiSelectProps["chipTextColor"];
  chipBackgroundColor?: CoreMultiSelectProps["chipBackgroundColor"];
  chipCloseIconColor?: CoreMultiSelectProps["chipCloseIconColor"];
}

function chipStyle(colors: ChipColors): CSSProperties {
  return {
    color: colors.chipTextColor
      ? resolveColorValue(colors.chipTextColor)
      : undefined,
    backgroundColor: colors.chipBackgroundColor
      ? resolveColorValue(colors.chipBackgroundColor)
      : undefined,
  };
}

function closeStyle(colors: ChipColors): CSSProperties {
  return {
    color: colors.chipCloseIconColor
      ? resolveColorValue(colors.chipCloseIconColor)
      : undefined,
  };
}

export interface MultiSelectProps extends CoreMultiSelectProps {
  renderOption?: (option: DropdownModel, selected: boolean) => ReactNode;
  renderChip?: (option: DropdownModel) => ReactNode;
  onChange?: (
    values: Array<string | number>,
    selectedOptions: DropdownModel[],
  ) => void;
  onSearchChange?: (query: string) => void;
  onLoadMore?: () => void;
}

export function MultiSelect({
  options,
  value = [],
  searchable = false,
  searchPlaceholder = "Search…",
  placeholder = "Select options",
  emptyText = "No options found",
  disabled = false,
  loading = false,
  hasMore = false,
  loadMoreText = "Load more",
  grouped = false,
  maxVisibleChips = 3,
  showCheckboxes = true,
  chipTextColor,
  chipBackgroundColor,
  chipCloseIconColor,
  renderOption,
  renderChip,
  onChange,
  onSearchChange,
  onLoadMore,
  ...props
}: MultiSelectProps) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const selected = options.filter((option) => value.includes(option.value));
  const visibleChips = selected.slice(0, maxVisibleChips);
  const matches = options.filter((option) =>
    String(option.display).toLowerCase().includes(query.toLowerCase()),
  );
  const groups = grouped
    ? Array.from(new Set(matches.map((option) => option.group ?? "Other")))
    : [undefined];
  const colors = {
    chipTextColor,
    chipBackgroundColor,
    chipCloseIconColor,
  };
  const flow = useFlowProps("fui-multi-select", props);
  const emit = (values: Array<string | number>) =>
    onChange?.(
      values,
      options.filter((option) => values.includes(option.value)),
    );
  const toggle = (option: DropdownModel) => {
    if (option.disabled) return;
    emit(
      value.includes(option.value)
        ? value.filter((item) => item !== option.value)
        : [...value, option.value],
    );
  };

  return (
    <div {...flow}>
      <div
        className="fui-multi-select-trigger"
        role="combobox"
        aria-expanded={open}
        tabIndex={disabled ? -1 : 0}
        onClick={() => !disabled && setOpen((current) => !current)}
        onKeyDown={(event) => {
          if (!disabled && (event.key === "Enter" || event.key === " ")) {
            event.preventDefault();
            setOpen((current) => !current);
          }
        }}
      >
        <span className="fui-chip-list">
          {visibleChips.length ? (
            visibleChips.map((option) => (
              <span
                className="fui-select-chip"
                style={chipStyle(colors)}
                key={option.value}
              >
                {renderChip?.(option) ?? option.display}
                <button
                  className="fui-select-chip-close"
                  style={closeStyle(colors)}
                  type="button"
                  aria-label={`Remove ${option.display}`}
                  disabled={disabled}
                  onKeyDown={(event) => event.stopPropagation()}
                  onClick={(event) => {
                    event.stopPropagation();
                    emit(value.filter((item) => item !== option.value));
                  }}
                >
                  <Icon icon="fa-solid fa-xmark" />
                </button>
              </span>
            ))
          ) : (
            <span className="fui-select-placeholder">{placeholder}</span>
          )}
          {selected.length > maxVisibleChips && (
            <span className="fui-select-chip-overflow">
              +{selected.length - maxVisibleChips}
            </span>
          )}
        </span>
        <button
          className="fui-multi-select-toggle"
          type="button"
          disabled={disabled}
          aria-label="Toggle options"
          aria-haspopup="listbox"
          aria-expanded={open}
          onKeyDown={(event) => event.stopPropagation()}
          onClick={(event) => {
            event.stopPropagation();
            setOpen((current) => !current);
          }}
        >
          <Icon icon={`fa-solid fa-chevron-${open ? "up" : "down"}`} />
        </button>
      </div>
      {open && (
        <div className="fui-select-menu">
          {searchable && (
            <label className="fui-select-search">
              <Icon icon="fa-solid fa-magnifying-glass" />
              <input
                value={query}
                placeholder={searchPlaceholder}
                autoFocus
                onChange={(event) => {
                  setQuery(event.target.value);
                  onSearchChange?.(event.target.value);
                }}
              />
            </label>
          )}
          <div
            className="fui-select-options"
            role="listbox"
            aria-multiselectable="true"
          >
            {matches.length ? (
              groups.map((group) => (
                <div key={String(group)}>
                  {grouped && <div className="fui-select-group">{group}</div>}
                  {matches
                    .filter(
                      (option) =>
                        !grouped || (option.group ?? "Other") === group,
                    )
                    .map((option) => {
                      const checked = value.includes(option.value);
                      return (
                        <button
                          className="fui-select-option"
                          key={option.value}
                          type="button"
                          role="option"
                          aria-selected={checked}
                          disabled={option.disabled}
                          onClick={() => toggle(option)}
                        >
                          {showCheckboxes && (
                            <input
                              type="checkbox"
                              checked={checked}
                              readOnly
                              tabIndex={-1}
                            />
                          )}
                          <span>
                            {renderOption?.(option, checked) ?? option.display}
                          </span>
                        </button>
                      );
                    })}
                </div>
              ))
            ) : (
              <div className="fui-select-empty">{emptyText}</div>
            )}
          </div>
          {(hasMore || loading) && (
            <button
              className="fui-select-load-more"
              type="button"
              disabled={loading}
              onClick={onLoadMore}
            >
              {loading ? "Loading…" : loadMoreText}
            </button>
          )}
        </div>
      )}
    </div>
  );
}

interface TreeNodeProps {
  node: TreeModel;
  values: Array<string | number>;
  expanded: Array<string | number>;
  cascade: boolean;
  depth: number;
  renderNode?: (node: TreeModel, selected: boolean) => ReactNode;
  onToggle: (node: TreeModel) => void;
  onExpand: (node: TreeModel) => void;
}

function TreeMultiNode({
  node,
  values,
  expanded,
  cascade,
  depth,
  renderNode,
  onToggle,
  onExpand,
}: TreeNodeProps) {
  const checkbox = useRef<HTMLInputElement>(null);
  const descendants = enabledSelectableDescendants(node);
  const selectedCount = descendants.filter((item) =>
    values.includes(item.value),
  ).length;
  const exactSelected = values.includes(node.value);
  const selected =
    cascade && descendants.length
      ? selectedCount === descendants.length
      : exactSelected;
  const indeterminate =
    cascade && selectedCount > 0 && selectedCount < descendants.length;
  useEffect(() => {
    if (checkbox.current) checkbox.current.indeterminate = indeterminate;
  }, [indeterminate]);
  const hasChildren = Boolean(node.children?.length || node.hasChildren);
  const isExpanded = expanded.includes(node.value);

  return (
    <div
      className="fui-tree-multi-node"
      role="treeitem"
      aria-expanded={hasChildren ? isExpanded : undefined}
    >
      <div
        className="fui-tree-multi-row"
        style={{ paddingLeft: `${depth * 1.25}rem` }}
      >
        <button
          className="fui-tree-multi-toggle"
          type="button"
          disabled={!hasChildren}
          onClick={() => onExpand(node)}
        >
          {hasChildren && (
            <Icon
              icon={`fa-solid fa-chevron-${isExpanded ? "down" : "right"}`}
            />
          )}
        </button>
        {node.selectable !== false && (
          <input
            ref={checkbox}
            type="checkbox"
            checked={selected}
            disabled={node.disabled}
            onChange={() => onToggle(node)}
          />
        )}
        <button
          className="fui-tree-multi-label"
          type="button"
          disabled={node.disabled}
          onClick={() =>
            node.selectable !== false ? onToggle(node) : onExpand(node)
          }
        >
          {renderNode?.(node, selected) ?? node.display}
        </button>
      </div>
      {hasChildren &&
        isExpanded &&
        node.children?.map((child) => (
          <TreeMultiNode
            key={child.value}
            node={child}
            values={values}
            expanded={expanded}
            cascade={cascade}
            depth={depth + 1}
            renderNode={renderNode}
            onToggle={onToggle}
            onExpand={onExpand}
          />
        ))}
    </div>
  );
}

export interface TreeMultiSelectProps extends CoreTreeMultiSelectProps {
  renderNode?: (node: TreeModel, selected: boolean) => ReactNode;
  renderChip?: (node: TreeModel) => ReactNode;
  onChange?: (
    values: Array<string | number>,
    selectedNodes: TreeModel[],
  ) => void;
  onExpandedValuesChange?: (values: Array<string | number>) => void;
  onSearchChange?: (query: string) => void;
  onLoadChildren?: (node: TreeModel) => void;
}

export function TreeMultiSelect({
  nodes,
  value = [],
  expandedValues,
  searchable = false,
  searchPlaceholder = "Search tree…",
  placeholder = "Select from tree",
  emptyText = "No nodes found",
  disabled = false,
  cascadeSelection = true,
  maxVisibleChips = 3,
  chipTextColor,
  chipBackgroundColor,
  chipCloseIconColor,
  renderNode,
  renderChip,
  onChange,
  onExpandedValuesChange,
  onSearchChange,
  onLoadChildren,
  ...props
}: TreeMultiSelectProps) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [internalExpanded, setInternalExpanded] = useState<
    Array<string | number>
  >([]);
  const expanded = expandedValues ?? internalExpanded;
  const selected = selectedTreeModels(nodes, value);
  const visibleChips = selected.slice(0, maxVisibleChips);
  const filtered = filterTree(nodes, query);
  const colors = { chipTextColor, chipBackgroundColor, chipCloseIconColor };
  const flow = useFlowProps("fui-tree-multi-select", props);
  const emit = (values: Array<string | number>) =>
    onChange?.(values, selectedTreeModels(nodes, values));
  const toggle = (node: TreeModel) => {
    if (node.disabled || node.selectable === false) return;
    const targets = cascadeSelection
      ? enabledSelectableDescendants(node).map((item) => item.value)
      : [node.value];
    const remove = targets.every((target) => value.includes(target));
    emit(
      remove
        ? value.filter((item) => !targets.includes(item))
        : Array.from(new Set([...value, ...targets])),
    );
  };
  const expand = (node: TreeModel) => {
    const next = expanded.includes(node.value)
      ? expanded.filter((item) => item !== node.value)
      : [...expanded, node.value];
    if (expandedValues === undefined) setInternalExpanded(next);
    onExpandedValuesChange?.(next);
    if (!node.children?.length && node.hasChildren) onLoadChildren?.(node);
  };

  return (
    <div {...flow}>
      <div
        className="fui-multi-select-trigger"
        role="combobox"
        aria-expanded={open}
        tabIndex={disabled ? -1 : 0}
        onClick={() => !disabled && setOpen((current) => !current)}
        onKeyDown={(event) => {
          if (!disabled && (event.key === "Enter" || event.key === " ")) {
            event.preventDefault();
            setOpen((current) => !current);
          }
        }}
      >
        <span className="fui-chip-list">
          {visibleChips.length ? (
            visibleChips.map((node) => (
              <span
                className="fui-select-chip"
                style={chipStyle(colors)}
                key={node.value}
              >
                {renderChip?.(node) ?? node.display}
                <button
                  className="fui-select-chip-close"
                  style={closeStyle(colors)}
                  type="button"
                  aria-label={`Remove ${node.display}`}
                  onKeyDown={(event) => event.stopPropagation()}
                  onClick={(event) => {
                    event.stopPropagation();
                    emit(value.filter((item) => item !== node.value));
                  }}
                >
                  <Icon icon="fa-solid fa-xmark" />
                </button>
              </span>
            ))
          ) : (
            <span className="fui-select-placeholder">{placeholder}</span>
          )}
          {selected.length > maxVisibleChips && (
            <span className="fui-select-chip-overflow">
              +{selected.length - maxVisibleChips}
            </span>
          )}
        </span>
        <button
          className="fui-multi-select-toggle"
          type="button"
          disabled={disabled}
          aria-label="Toggle tree"
          aria-expanded={open}
          onKeyDown={(event) => event.stopPropagation()}
          onClick={(event) => {
            event.stopPropagation();
            setOpen((current) => !current);
          }}
        >
          <Icon icon={`fa-solid fa-chevron-${open ? "up" : "down"}`} />
        </button>
      </div>
      {open && (
        <div className="fui-select-menu">
          {searchable && (
            <label className="fui-select-search">
              <Icon icon="fa-solid fa-magnifying-glass" />
              <input
                value={query}
                placeholder={searchPlaceholder}
                autoFocus
                onChange={(event) => {
                  setQuery(event.target.value);
                  onSearchChange?.(event.target.value);
                }}
              />
            </label>
          )}
          <div className="fui-tree-multi" role="tree">
            {filtered.length ? (
              filtered.map((node) => (
                <TreeMultiNode
                  key={node.value}
                  node={node}
                  values={value}
                  expanded={
                    query
                      ? flattenTree(filtered).map((item) => item.value)
                      : expanded
                  }
                  cascade={cascadeSelection}
                  depth={0}
                  renderNode={renderNode}
                  onToggle={toggle}
                  onExpand={expand}
                />
              ))
            ) : (
              <div className="fui-select-empty">{emptyText}</div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
