// packages/react/src/advanced.tsx
import {
  Children,
  cloneElement,
  isValidElement,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ChangeEvent,
  type PropsWithChildren,
  type ReactElement,
  type ReactNode,
} from "react";
import type {
  AutocompleteProps as CoreAutocompleteProps,
  BreadcrumbItem,
  BreadcrumbProps as CoreBreadcrumbProps,
  CarouselProps as CoreCarouselProps,
  DateTimeProps as CoreDateTimeProps,
  DropdownModel,
  FileUploadProps as CoreFileUploadProps,
  ListboxProps as CoreListboxProps,
  NotificationProps as CoreNotificationProps,
  PopoverProps as CorePopoverProps,
  RatingProps as CoreRatingProps,
  TimelineItem,
  TimelineProps as CoreTimelineProps,
} from "@akin2unde/flowui-core";
import { setLocalDayBoundary } from "@akin2unde/flowui-core";
import { useFlowProps } from "./helpers";
import { Icon } from "./primitives";

export interface DateTimeProps extends CoreDateTimeProps {
  onChange?: (value: string) => void;
}

const dateKey = (date: Date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

const calendarDays = (month: Date) => {
  const first = new Date(month.getFullYear(), month.getMonth(), 1);
  const start = new Date(first);
  start.setDate(1 - first.getDay());
  return Array.from({ length: 42 }, (_, index) => {
    const day = new Date(start);
    day.setDate(start.getDate() + index);
    return day;
  });
};

export function DateTime({
  value,
  mode = "datetime",
  name,
  min,
  max,
  disabled,
  showDayBoundaryButtons = true,
  onChange,
  ...props
}: DateTimeProps) {
  const flow = useFlowProps("fui-date-time", props);
  const selectedDate = value?.split("T")[0] ?? "";
  const selectedTime = value?.includes("T") ? value.split("T")[1] : "00:00";
  const parsed = selectedDate ? new Date(`${selectedDate}T12:00`) : new Date();
  const [open, setOpen] = useState(false);
  const [month, setMonth] = useState(
    new Date(parsed.getFullYear(), parsed.getMonth(), 1),
  );
  const selectDate = (key: string) => {
    onChange?.(mode === "date" ? key : `${key}T${selectedTime || "00:00"}`);
    setOpen(false);
  };
  const selectToday = () => {
    const today = dateKey(new Date());
    selectDate(today);
    setMonth(new Date());
  };

  if (mode === "time") {
    return (
      <div {...flow}>
        <input
          className="fui-control"
          type="time"
          value={value ?? ""}
          name={name}
          min={min}
          max={max}
          disabled={disabled}
          onChange={(event) => onChange?.(event.target.value)}
        />
      </div>
    );
  }

  return (
    <div {...flow}>
      <input type="hidden" name={name} value={value ?? ""} />
      <div className="fui-date-time-field">
        <button
          className="fui-date-display"
          type="button"
          disabled={disabled}
          onClick={() => {
            setMonth(new Date(parsed.getFullYear(), parsed.getMonth(), 1));
            setOpen((current) => !current);
          }}
        >
          <Icon icon="fa-regular fa-calendar" />
          <span>{selectedDate || "Select date"}</span>
        </button>
        {mode === "datetime" && (
          <input
            className="fui-date-time-clock"
            type="time"
            value={selectedTime}
            disabled={disabled}
            onChange={(event) =>
              onChange?.(
                `${selectedDate || dateKey(new Date())}T${event.target.value}`,
              )
            }
          />
        )}
        <div className="fui-date-time-actions">
          <button
            type="button"
            title="Today"
            disabled={disabled}
            onClick={selectToday}
          >
            <Icon icon="fa-solid fa-calendar-day" />
          </button>
          {mode === "datetime" && showDayBoundaryButtons && (
            <>
              <button
                type="button"
                title="Start of day"
                disabled={disabled}
                onClick={() => onChange?.(setLocalDayBoundary(value, "start"))}
              >
                <Icon icon="fa-solid fa-sun" />
              </button>
              <button
                type="button"
                title="End of day"
                disabled={disabled}
                onClick={() => onChange?.(setLocalDayBoundary(value, "end"))}
              >
                <Icon icon="fa-solid fa-moon" />
              </button>
            </>
          )}
        </div>
      </div>
      {open && (
        <div className="fui-calendar" role="dialog" aria-label="Choose date">
          <div className="fui-calendar-header">
            <button
              type="button"
              aria-label="Previous month"
              onClick={() =>
                setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))
              }
            >
              <Icon icon="fa-solid fa-chevron-left" />
            </button>
            <strong>
              {month.toLocaleDateString(undefined, {
                month: "long",
                year: "numeric",
              })}
            </strong>
            <button
              type="button"
              aria-label="Next month"
              onClick={() =>
                setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))
              }
            >
              <Icon icon="fa-solid fa-chevron-right" />
            </button>
          </div>
          <div className="fui-calendar-grid fui-calendar-weekdays">
            {["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"].map((day) => (
              <span key={day}>{day}</span>
            ))}
          </div>
          <div className="fui-calendar-grid">
            {calendarDays(month).map((day) => {
              const key = dateKey(day);
              return (
                <button
                  key={key}
                  type="button"
                  data-outside={day.getMonth() !== month.getMonth()}
                  data-selected={key === selectedDate}
                  data-today={key === dateKey(new Date())}
                  disabled={Boolean(
                    (min && key < min.split("T")[0]) ||
                    (max && key > max.split("T")[0]),
                  )}
                  onClick={() => selectDate(key)}
                >
                  {day.getDate()}
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

export interface AutocompleteProps extends CoreAutocompleteProps {
  onChange?: (option: DropdownModel) => void;
}

export function Autocomplete({
  options,
  value,
  placeholder,
  minCharacters = 1,
  disabled,
  onChange,
  ...props
}: AutocompleteProps) {
  const selected = options.find((option) => option.value === value);
  const [query, setQuery] = useState(selected ? String(selected.display) : "");
  const [open, setOpen] = useState(false);
  const flow = useFlowProps("fui-autocomplete", props);
  const matches = options.filter((option) =>
    String(option.display).toLowerCase().includes(query.toLowerCase()),
  );

  useEffect(() => {
    if (selected) setQuery(String(selected.display));
  }, [selected?.value]);

  return (
    <div {...flow}>
      <input
        className="fui-control"
        value={query}
        placeholder={placeholder}
        disabled={disabled}
        role="combobox"
        aria-expanded={open}
        onFocus={() => setOpen(true)}
        onChange={(event) => {
          setQuery(event.target.value);
          setOpen(true);
        }}
      />
      {open && query.length >= minCharacters && (
        <div className="fui-autocomplete-menu" role="listbox">
          {matches.length ? (
            matches.map((option) => (
              <button
                key={option.value}
                type="button"
                role="option"
                aria-selected={value === option.value}
                onMouseDown={(event) => event.preventDefault()}
                onClick={() => {
                  setQuery(String(option.display));
                  setOpen(false);
                  onChange?.(option);
                }}
              >
                {option.display}
              </button>
            ))
          ) : (
            <span className="fui-empty">No matches</span>
          )}
        </div>
      )}
    </div>
  );
}

export interface RatingProps extends CoreRatingProps {
  onChange?: (value: number) => void;
}

export function Rating({
  value = 0,
  maximum = 5,
  precision = 1,
  readOnly,
  disabled,
  onChange,
  ...props
}: RatingProps) {
  const flow = useFlowProps("fui-rating", props);
  const points = Array.from(
    { length: maximum / precision },
    (_, index) => (index + 1) * precision,
  );

  return (
    <div {...flow} role="radiogroup" aria-label="Rating">
      {points.map((point) => (
        <button
          key={point}
          className={point <= value ? "fui-rating-active" : ""}
          type="button"
          role="radio"
          aria-checked={point === value}
          aria-label={`${point} out of ${maximum}`}
          disabled={disabled || readOnly}
          onClick={() => onChange?.(point)}
        >
          <Icon icon="fa-solid fa-star" />
        </button>
      ))}
    </div>
  );
}

export interface ListboxProps extends CoreListboxProps {
  values?: Array<string | number>;
  renderOption?: (option: DropdownModel, selected: boolean) => ReactNode;
  onChange?: (option: DropdownModel) => void;
  onValuesChange?: (options: DropdownModel[]) => void;
}

export function Listbox({
  options,
  value,
  values = [],
  multiple,
  disabled,
  renderOption,
  onChange,
  onValuesChange,
  ...props
}: ListboxProps) {
  const flow = useFlowProps("fui-listbox", props);
  const selectedValues = multiple ? values : value === undefined ? [] : [value];

  const select = (option: DropdownModel) => {
    if (!multiple) return onChange?.(option);
    const next = selectedValues.includes(option.value)
      ? selectedValues.filter((item) => item !== option.value)
      : [...selectedValues, option.value];
    onValuesChange?.(options.filter((item) => next.includes(item.value)));
  };

  return (
    <div {...flow} role="listbox" aria-multiselectable={multiple}>
      {options.map((option) => {
        const selectedOption = selectedValues.includes(option.value);
        return (
          <button
            key={option.value}
            type="button"
            role="option"
            aria-selected={selectedOption}
            disabled={disabled}
            onClick={() => select(option)}
          >
            {renderOption?.(option, selectedOption) ?? option.display}
          </button>
        );
      })}
    </div>
  );
}

export interface TimelineProps extends CoreTimelineProps {
  renderItem?: (item: TimelineItem) => ReactNode;
}

export function Timeline({
  items,
  orientation = "vertical",
  renderItem,
  ...props
}: TimelineProps) {
  const flow = useFlowProps("fui-timeline", props);
  return (
    <ol {...flow} data-orientation={orientation}>
      {items.map((item) => (
        <li key={item.id} className="fui-timeline-item">
          <span className="fui-timeline-marker">
            {item.image ? (
              <img src={item.image} alt="" />
            ) : (
              <Icon icon={item.icon ?? "fa-solid fa-circle"} />
            )}
          </span>
          <div className="fui-timeline-content">
            {renderItem?.(item) ?? (
              <>
                <strong>{item.title}</strong>
                {item.description && <p>{item.description}</p>}
                {item.date && <time>{item.date}</time>}
              </>
            )}
          </div>
        </li>
      ))}
    </ol>
  );
}

export interface PopoverProps extends PropsWithChildren<CorePopoverProps> {
  trigger: ReactElement;
  onOpenChange?: (open: boolean) => void;
}

export function Popover({
  trigger,
  children,
  open,
  placement = "bottom",
  closeOnOutsideClick = true,
  onOpenChange,
  ...props
}: PopoverProps) {
  const [internalOpen, setInternalOpen] = useState(false);
  const shown = open ?? internalOpen;
  const root = useRef<HTMLSpanElement>(null);
  const flow = useFlowProps("fui-popover", props);
  const setShown = (next: boolean) => {
    if (open === undefined) setInternalOpen(next);
    onOpenChange?.(next);
  };

  useEffect(() => {
    if (!shown || !closeOnOutsideClick) return;
    const close = (event: MouseEvent) => {
      if (!root.current?.contains(event.target as Node)) setShown(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, [shown, closeOnOutsideClick]);

  return (
    <span {...flow} ref={root} data-placement={placement}>
      {cloneElement(trigger, {
        onClick: () => setShown(!shown),
        "aria-expanded": shown,
      } as Record<string, unknown>)}
      {shown && <div className="fui-popover-content">{children}</div>}
    </span>
  );
}

export interface FilePreview {
  file: File;
  url?: string;
}
export interface FileUploadProps extends CoreFileUploadProps {
  onChange?: (files: File[]) => void;
}

export function FileUpload({
  accept,
  multiple,
  preview = true,
  maxSize,
  disabled,
  onChange,
  ...props
}: FileUploadProps) {
  const [files, setFiles] = useState<FilePreview[]>([]);
  const flow = useFlowProps("fui-file-upload", props);

  useEffect(
    () => () =>
      files.forEach((item) => item.url && URL.revokeObjectURL(item.url)),
    [files],
  );

  const choose = (event: ChangeEvent<HTMLInputElement>) => {
    const accepted = Array.from(event.target.files ?? []).filter(
      (file) => !maxSize || file.size <= maxSize,
    );
    setFiles(
      accepted.map((file) => ({
        file,
        url:
          preview && file.type.startsWith("image/")
            ? URL.createObjectURL(file)
            : undefined,
      })),
    );
    onChange?.(accepted);
  };

  return (
    <div {...flow}>
      <label className="fui-file-drop">
        <Icon icon="fa-solid fa-cloud-arrow-up" />
        <span>Choose file{multiple ? "s" : ""}</span>
        <input
          type="file"
          accept={accept}
          multiple={multiple}
          disabled={disabled}
          onChange={choose}
        />
      </label>
      {preview && files.length > 0 && (
        <div className="fui-file-previews">
          {files.map(({ file, url }) => (
            <div key={`${file.name}-${file.lastModified}`}>
              {url ? (
                <img src={url} alt={file.name} />
              ) : (
                <Icon icon="fa-solid fa-file" />
              )}
              <span>{file.name}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export interface CarouselProps extends PropsWithChildren<CoreCarouselProps> {
  onChange?: (index: number) => void;
}

export function Carousel({
  children,
  activeIndex,
  loop = true,
  showIndicators = true,
  showControls = true,
  onChange,
  ...props
}: CarouselProps) {
  const slides = Children.toArray(children);
  const [internalIndex, setInternalIndex] = useState(0);
  const index = activeIndex ?? internalIndex;
  const flow = useFlowProps("fui-carousel", props);
  const select = (next: number) => {
    const resolved = loop
      ? (next + slides.length) % slides.length
      : Math.max(0, Math.min(next, slides.length - 1));
    if (activeIndex === undefined) setInternalIndex(resolved);
    onChange?.(resolved);
  };

  return (
    <div {...flow}>
      <div className="fui-carousel-slide">{slides[index]}</div>
      {showControls && slides.length > 1 && (
        <>
          <button
            className="fui-carousel-prev"
            type="button"
            onClick={() => select(index - 1)}
            aria-label="Previous slide"
          >
            <Icon icon="fa-solid fa-chevron-left" />
          </button>
          <button
            className="fui-carousel-next"
            type="button"
            onClick={() => select(index + 1)}
            aria-label="Next slide"
          >
            <Icon icon="fa-solid fa-chevron-right" />
          </button>
        </>
      )}
      {showIndicators && (
        <div className="fui-carousel-indicators">
          {slides.map((_, itemIndex) => (
            <button
              key={itemIndex}
              type="button"
              aria-label={`Slide ${itemIndex + 1}`}
              aria-current={itemIndex === index}
              onClick={() => select(itemIndex)}
            />
          ))}
        </div>
      )}
    </div>
  );
}

export interface BreadcrumbProps extends CoreBreadcrumbProps {
  renderItem?: (item: BreadcrumbItem) => ReactNode;
  onSelect?: (item: BreadcrumbItem) => void;
}

export function Breadcrumb({
  items,
  separatorIcon = "fa-solid fa-chevron-right",
  renderItem,
  onSelect,
  ...props
}: BreadcrumbProps) {
  const flow = useFlowProps("fui-breadcrumb", props);
  return (
    <nav {...flow} aria-label="Breadcrumb">
      <ol>
        {items.map((item, index) => (
          <li key={item.id}>
            {index > 0 && <Icon icon={separatorIcon} />}
            <a
              href={item.href}
              aria-current={index === items.length - 1 ? "page" : undefined}
              onClick={(event) => {
                if (!item.href) event.preventDefault();
                onSelect?.(item);
              }}
            >
              {renderItem?.(item) ?? (
                <>
                  {item.image && <img src={item.image} alt="" />}
                  {item.icon && <Icon icon={item.icon} />}
                  {item.text && <span>{item.text}</span>}
                </>
              )}
            </a>
          </li>
        ))}
      </ol>
    </nav>
  );
}

export interface NotificationProps extends PropsWithChildren<CoreNotificationProps> {
  title?: string;
  onClose?: () => void;
}

export function Notification({
  children,
  title,
  open = true,
  type = "info",
  horizontal = "right",
  vertical = "top",
  duration = 0,
  dismissible = true,
  onClose,
  ...props
}: NotificationProps) {
  const flow = useFlowProps("fui-notification", props);
  useEffect(() => {
    if (!open || duration <= 0) return;
    const timer = window.setTimeout(() => onClose?.(), duration);
    return () => window.clearTimeout(timer);
  }, [open, duration, onClose]);
  if (!open) return null;
  const icons = {
    success: "fa-circle-check",
    error: "fa-circle-xmark",
    warning: "fa-triangle-exclamation",
    info: "fa-circle-info",
  };
  return (
    <aside
      {...flow}
      data-type={type}
      data-horizontal={horizontal}
      data-vertical={vertical}
      role={type === "error" ? "alert" : "status"}
    >
      <Icon icon={`fa-solid ${icons[type]}`} />
      <div>
        {title && <strong>{title}</strong>}
        {children}
      </div>
      {dismissible && (
        <button type="button" aria-label="Close notification" onClick={onClose}>
          <Icon icon="fa-solid fa-xmark" />
        </button>
      )}
    </aside>
  );
}

// packages/angular/src/lib/advanced.ts
import { CommonModule } from "@angular/common";
import {
  Component,
  ContentChildren,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  QueryList,
  TemplateRef,
} from "@angular/core";
import type {
  BreadcrumbItem,
  DateTimeMode,
  DropdownModel,
  NotificationHorizontal,
  NotificationType,
  NotificationVertical,
  Orientation,
  TimelineItem,
  TooltipLocation,
} from "@akin2unde/flowui-core";
import { setLocalDayBoundary } from "@akin2unde/flowui-core";
import { FlowComponentBase } from "./base";
import { FlowIconComponent } from "./primitives";

@Component({
  selector: "fui-date-time",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <input
        *ngIf="mode === 'time'"
        class="fui-control"
        type="time"
        [value]="value"
        [name]="name ?? ''"
        [min]="min ?? ''"
        [max]="max ?? ''"
        [disabled]="disabled"
        (input)="valueChange.emit($any($event.target).value)"
      />

      <div *ngIf="mode !== 'time'" class="fui-date-time-field">
        <button
          class="fui-date-display"
          type="button"
          [disabled]="disabled"
          (click)="toggleCalendar()"
        >
          <fui-icon icon="fa-regular fa-calendar" />
          <span>{{ selectedDate || "Select date" }}</span>
        </button>
        <input
          *ngIf="mode === 'datetime'"
          class="fui-date-time-clock"
          type="time"
          [value]="selectedTime"
          [disabled]="disabled"
          (input)="setTime($any($event.target).value)"
        />
        <div class="fui-date-time-actions">
          <button
            type="button"
            title="Today"
            [disabled]="disabled"
            (click)="selectToday()"
          >
            <fui-icon icon="fa-solid fa-calendar-day" />
          </button>
          <button
            *ngIf="mode === 'datetime' && showDayBoundaryButtons"
            type="button"
            title="Start of day"
            [disabled]="disabled"
            (click)="setBoundary('start')"
          >
            <fui-icon icon="fa-solid fa-sun" />
          </button>
          <button
            *ngIf="mode === 'datetime' && showDayBoundaryButtons"
            type="button"
            title="End of day"
            [disabled]="disabled"
            (click)="setBoundary('end')"
          >
            <fui-icon icon="fa-solid fa-moon" />
          </button>
        </div>
      </div>

      <div *ngIf="open && mode !== 'time'" class="fui-calendar" role="dialog">
        <div class="fui-calendar-header">
          <button
            type="button"
            aria-label="Previous month"
            (click)="moveMonth(-1)"
          >
            <fui-icon icon="fa-solid fa-chevron-left" />
          </button>
          <strong>{{ monthLabel }}</strong>
          <button type="button" aria-label="Next month" (click)="moveMonth(1)">
            <fui-icon icon="fa-solid fa-chevron-right" />
          </button>
        </div>
        <div class="fui-calendar-grid fui-calendar-weekdays">
          <span *ngFor="let weekday of weekdays">{{ weekday }}</span>
        </div>
        <div class="fui-calendar-grid">
          <button
            *ngFor="let day of days"
            type="button"
            [attr.data-outside]="day.getMonth() !== month.getMonth()"
            [attr.data-selected]="dateKey(day) === selectedDate"
            [attr.data-today]="dateKey(day) === dateKey(today)"
            [disabled]="dayDisabled(day)"
            (click)="selectDate(dateKey(day))"
          >
            {{ day.getDate() }}
          </button>
        </div>
      </div>
    </div>
  `,
})
export class FlowDateTimeComponent extends FlowComponentBase {
  @Input() value = "";
  @Input() mode: DateTimeMode = "datetime";
  @Input() name?: string;
  @Input() min?: string;
  @Input() max?: string;
  @Input() disabled = false;
  @Input() showDayBoundaryButtons = true;
  @Output() valueChange = new EventEmitter<string>();
  open = false;
  month = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
  readonly today = new Date();
  readonly weekdays = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];

  get selectedDate(): string {
    return this.value.split("T")[0] ?? "";
  }

  get selectedTime(): string {
    return this.value.includes("T") ? this.value.split("T")[1] : "00:00";
  }

  get monthLabel(): string {
    return this.month.toLocaleDateString(undefined, {
      month: "long",
      year: "numeric",
    });
  }

  get days(): Date[] {
    const first = new Date(this.month.getFullYear(), this.month.getMonth(), 1);
    const start = new Date(first);
    start.setDate(1 - first.getDay());
    return Array.from({ length: 42 }, (_, index) => {
      const day = new Date(start);
      day.setDate(start.getDate() + index);
      return day;
    });
  }

  dateKey(date: Date): string {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
  }

  dayDisabled(date: Date): boolean {
    const key = this.dateKey(date);
    return Boolean(
      (this.min && key < this.min.split("T")[0]) ||
      (this.max && key > this.max.split("T")[0]),
    );
  }

  selectDate(date: string): void {
    this.valueChange.emit(
      this.mode === "date" ? date : `${date}T${this.selectedTime || "00:00"}`,
    );
    this.open = false;
  }

  selectToday(): void {
    this.selectDate(this.dateKey(this.today));
    this.month = new Date(this.today.getFullYear(), this.today.getMonth(), 1);
  }

  setTime(time: string): void {
    this.valueChange.emit(
      `${this.selectedDate || this.dateKey(this.today)}T${time}`,
    );
  }

  moveMonth(amount: number): void {
    this.month = new Date(
      this.month.getFullYear(),
      this.month.getMonth() + amount,
      1,
    );
  }

  toggleCalendar(): void {
    if (!this.open && this.selectedDate) {
      const selected = new Date(`${this.selectedDate}T12:00`);
      this.month = new Date(selected.getFullYear(), selected.getMonth(), 1);
    }
    this.open = !this.open;
  }

  setBoundary(boundary: "start" | "end"): void {
    this.valueChange.emit(setLocalDayBoundary(this.value, boundary));
  }

  view = () => this.resolved("fui-date-time");
}

@Component({
  selector: "fui-autocomplete",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <input
        class="fui-control"
        role="combobox"
        [value]="query"
        [placeholder]="placeholder ?? ''"
        [disabled]="disabled"
        [attr.aria-expanded]="open"
        (focus)="open = true"
        (input)="updateQuery($any($event.target).value)"
      />

      <div
        *ngIf="open && query.length >= minCharacters"
        class="fui-autocomplete-menu"
        role="listbox"
      >
        <button
          *ngFor="let option of matches"
          type="button"
          role="option"
          [attr.aria-selected]="value === option.value"
          (mousedown)="$event.preventDefault()"
          (click)="select(option)"
        >
          {{ option.display }}
        </button>
        <span *ngIf="matches.length === 0" class="fui-empty">No matches</span>
      </div>
    </div>
  `,
})
export class FlowAutocompleteComponent extends FlowComponentBase {
  @Input() options: DropdownModel[] = [];
  @Input() value?: string | number;
  @Input() placeholder?: string;
  @Input() minCharacters = 1;
  @Input() disabled = false;
  @Output() selected = new EventEmitter<DropdownModel>();

  query = "";
  open = false;

  get matches(): DropdownModel[] {
    const search = this.query.toLowerCase();
    return this.options.filter((option) =>
      String(option.display).toLowerCase().includes(search),
    );
  }

  updateQuery(query: string): void {
    this.query = query;
    this.open = true;
  }

  select(option: DropdownModel): void {
    this.query = String(option.display);
    this.open = false;
    this.selected.emit(option);
  }

  view = () => this.resolved("fui-autocomplete");
}

@Component({
  selector: "fui-rating",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <div
      [class]="view().className"
      [ngStyle]="view().style"
      role="radiogroup"
      aria-label="Rating"
    >
      <button
        *ngFor="let point of points"
        type="button"
        role="radio"
        [class.fui-rating-active]="point <= value"
        [attr.aria-checked]="point === value"
        [attr.aria-label]="point + ' out of ' + maximum"
        [disabled]="disabled || readOnly"
        (click)="valueChange.emit(point)"
      >
        <fui-icon icon="fa-solid fa-star" />
      </button>
    </div>
  `,
})
export class FlowRatingComponent extends FlowComponentBase {
  @Input() value = 0;
  @Input() maximum = 5;
  @Input() precision: 1 | 0.5 = 1;
  @Input() readOnly = false;
  @Input() disabled = false;
  @Output() valueChange = new EventEmitter<number>();

  get points(): number[] {
    return Array.from(
      { length: this.maximum / this.precision },
      (_, index) => (index + 1) * this.precision,
    );
  }

  view = () => this.resolved("fui-rating");
}

@Component({
  selector: "fui-listbox",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      [class]="view().className"
      [ngStyle]="view().style"
      role="listbox"
      [attr.aria-multiselectable]="multiple"
    >
      <button
        *ngFor="let option of options"
        type="button"
        role="option"
        [disabled]="disabled"
        [attr.aria-selected]="isSelected(option)"
        (click)="select(option)"
      >
        <ng-container
          *ngIf="optionTemplate; else defaultOption"
          [ngTemplateOutlet]="optionTemplate"
          [ngTemplateOutletContext]="{
            $implicit: option,
            selected: isSelected(option),
          }"
        />
        <ng-template #defaultOption>{{ option.display }}</ng-template>
      </button>
    </div>
  `,
})
export class FlowListboxComponent extends FlowComponentBase {
  @Input() options: DropdownModel[] = [];
  @Input() value?: string | number;
  @Input() values: Array<string | number> = [];
  @Input() multiple = false;
  @Input() disabled = false;
  @Input() optionTemplate?: TemplateRef<{
    $implicit: DropdownModel;
    selected: boolean;
  }>;
  @Output() selected = new EventEmitter<DropdownModel>();
  @Output() valuesChange = new EventEmitter<DropdownModel[]>();

  isSelected(option: DropdownModel): boolean {
    return this.multiple
      ? this.values.includes(option.value)
      : this.value === option.value;
  }

  select(option: DropdownModel): void {
    if (!this.multiple) {
      this.selected.emit(option);
      return;
    }
    const next = this.values.includes(option.value)
      ? this.values.filter((value) => value !== option.value)
      : [...this.values, option.value];
    this.valuesChange.emit(
      this.options.filter((item) => next.includes(item.value)),
    );
  }

  view = () => this.resolved("fui-listbox");
}

@Component({
  selector: "fui-timeline",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <ol
      [class]="view().className"
      [ngStyle]="view().style"
      [attr.data-orientation]="orientation"
    >
      <li *ngFor="let item of items" class="fui-timeline-item">
        <span class="fui-timeline-marker">
          <img
            *ngIf="item.image; else timelineIcon"
            [src]="item.image"
            alt=""
          />
          <ng-template #timelineIcon>
            <fui-icon [icon]="item.icon ?? 'fa-solid fa-circle'" />
          </ng-template>
        </span>
        <div class="fui-timeline-content">
          <ng-container
            *ngIf="itemTemplate; else defaultItem"
            [ngTemplateOutlet]="itemTemplate"
            [ngTemplateOutletContext]="{ $implicit: item }"
          />
          <ng-template #defaultItem>
            <strong>{{ item.title }}</strong>
            <p *ngIf="item.description">{{ item.description }}</p>
            <time *ngIf="item.date">{{ item.date }}</time>
          </ng-template>
        </div>
      </li>
    </ol>
  `,
})
export class FlowTimelineComponent extends FlowComponentBase {
  @Input() items: TimelineItem[] = [];
  @Input() orientation: Orientation = "vertical";
  @Input() itemTemplate?: TemplateRef<{ $implicit: TimelineItem }>;
  view = () => this.resolved("fui-timeline");
}

@Component({
  selector: "fui-popover",
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      [class]="view().className"
      [ngStyle]="view().style"
      [attr.data-placement]="placement"
    >
      <span class="fui-popover-trigger" (click)="toggle()">
        <ng-content />
      </span>
      <div *ngIf="isOpen" class="fui-popover-content">
        <ng-container *ngIf="content" [ngTemplateOutlet]="content" />
      </div>
    </span>
  `,
})
export class FlowPopoverComponent extends FlowComponentBase {
  @Input() open?: boolean;
  @Input() placement: TooltipLocation = "bottom";
  @Input() closeOnOutsideClick = true;
  @Input() content?: TemplateRef<unknown>;
  @Output() openChange = new EventEmitter<boolean>();
  private internalOpen = false;

  constructor(private readonly element: ElementRef<HTMLElement>) {
    super();
  }

  get isOpen(): boolean {
    return this.open ?? this.internalOpen;
  }

  toggle(): void {
    this.setOpen(!this.isOpen);
  }

  private setOpen(value: boolean): void {
    if (this.open === undefined) this.internalOpen = value;
    this.openChange.emit(value);
  }

  @HostListener("document:mousedown", ["$event"])
  outsideClick(event: MouseEvent): void {
    if (
      this.isOpen &&
      this.closeOnOutsideClick &&
      !this.element.nativeElement.contains(event.target as Node)
    ) {
      this.setOpen(false);
    }
  }

  view = () => this.resolved("fui-popover");
}

interface AngularFilePreview {
  file: File;
  url?: string;
}

@Component({
  selector: "fui-file-upload",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <label class="fui-file-drop">
        <fui-icon icon="fa-solid fa-cloud-arrow-up" />
        <span>Choose file{{ multiple ? "s" : "" }}</span>
        <input
          type="file"
          [accept]="accept ?? ''"
          [multiple]="multiple"
          [disabled]="disabled"
          (change)="choose($event)"
        />
      </label>
      <div *ngIf="preview && files.length" class="fui-file-previews">
        <div *ngFor="let item of files">
          <img
            *ngIf="item.url; else fileIcon"
            [src]="item.url"
            [alt]="item.file.name"
          />
          <ng-template #fileIcon
            ><fui-icon icon="fa-solid fa-file"
          /></ng-template>
          <span>{{ item.file.name }}</span>
        </div>
      </div>
    </div>
  `,
})
export class FlowFileUploadComponent extends FlowComponentBase {
  @Input() accept?: string;
  @Input() multiple = false;
  @Input() preview = true;
  @Input() maxSize?: number;
  @Input() disabled = false;
  @Output() filesChange = new EventEmitter<File[]>();
  files: AngularFilePreview[] = [];

  choose(event: Event): void {
    this.files.forEach((item) => item.url && URL.revokeObjectURL(item.url));
    const input = event.target as HTMLInputElement;
    const chosen = Array.from(input.files ?? []).filter(
      (file) => !this.maxSize || file.size <= this.maxSize,
    );
    this.files = chosen.map((file) => ({
      file,
      url:
        this.preview && file.type.startsWith("image/")
          ? URL.createObjectURL(file)
          : undefined,
    }));
    this.filesChange.emit(chosen);
  }

  view = () => this.resolved("fui-file-upload");
}

@Component({
  selector: "fui-carousel",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <div [class]="view().className" [ngStyle]="view().style">
      <div class="fui-carousel-slide">
        <ng-container
          *ngIf="slides[resolvedIndex]"
          [ngTemplateOutlet]="slides[resolvedIndex]"
        />
      </div>
      <button
        *ngIf="showControls && slides.length > 1"
        class="fui-carousel-prev"
        type="button"
        aria-label="Previous slide"
        (click)="select(resolvedIndex - 1)"
      >
        <fui-icon icon="fa-solid fa-chevron-left" />
      </button>
      <button
        *ngIf="showControls && slides.length > 1"
        class="fui-carousel-next"
        type="button"
        aria-label="Next slide"
        (click)="select(resolvedIndex + 1)"
      >
        <fui-icon icon="fa-solid fa-chevron-right" />
      </button>
      <div *ngIf="showIndicators" class="fui-carousel-indicators">
        <button
          *ngFor="let slide of slides; let index = index"
          type="button"
          [attr.aria-label]="'Slide ' + (index + 1)"
          [attr.aria-current]="index === resolvedIndex"
          (click)="select(index)"
        ></button>
      </div>
    </div>
  `,
})
export class FlowCarouselComponent extends FlowComponentBase {
  @ContentChildren(TemplateRef)
  slideTemplates!: QueryList<TemplateRef<unknown>>;
  @Input() activeIndex?: number;
  @Input() loop = true;
  @Input() showIndicators = true;
  @Input() showControls = true;
  @Output() activeIndexChange = new EventEmitter<number>();
  private internalIndex = 0;

  get slides(): TemplateRef<unknown>[] {
    return this.slideTemplates?.toArray() ?? [];
  }

  get resolvedIndex(): number {
    return this.activeIndex ?? this.internalIndex;
  }

  select(index: number): void {
    if (!this.slides.length) return;
    const next = this.loop
      ? (index + this.slides.length) % this.slides.length
      : Math.max(0, Math.min(index, this.slides.length - 1));
    if (this.activeIndex === undefined) this.internalIndex = next;
    this.activeIndexChange.emit(next);
  }

  view = () => this.resolved("fui-carousel");
}

@Component({
  selector: "fui-breadcrumb",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <nav
      [class]="view().className"
      [ngStyle]="view().style"
      aria-label="Breadcrumb"
    >
      <ol>
        <li *ngFor="let item of items; let index = index">
          <fui-icon *ngIf="index > 0" [icon]="separatorIcon" />
          <a
            [href]="item.href ?? ''"
            [attr.aria-current]="index === items.length - 1 ? 'page' : null"
            (click)="select($event, item)"
          >
            <ng-container
              *ngIf="itemTemplate; else defaultCrumb"
              [ngTemplateOutlet]="itemTemplate"
              [ngTemplateOutletContext]="{ $implicit: item }"
            />
            <ng-template #defaultCrumb>
              <img *ngIf="item.image" [src]="item.image" alt="" />
              <fui-icon *ngIf="item.icon" [icon]="item.icon" />
              <span *ngIf="item.text">{{ item.text }}</span>
            </ng-template>
          </a>
        </li>
      </ol>
    </nav>
  `,
})
export class FlowBreadcrumbComponent extends FlowComponentBase {
  @Input() items: BreadcrumbItem[] = [];
  @Input() separatorIcon = "fa-solid fa-chevron-right";
  @Input() itemTemplate?: TemplateRef<{ $implicit: BreadcrumbItem }>;
  @Output() selected = new EventEmitter<BreadcrumbItem>();

  select(event: MouseEvent, item: BreadcrumbItem): void {
    if (!item.href) event.preventDefault();
    this.selected.emit(item);
  }

  view = () => this.resolved("fui-breadcrumb");
}

@Component({
  selector: "fui-notification",
  standalone: true,
  imports: [CommonModule, FlowIconComponent],
  template: `
    <aside
      *ngIf="open"
      [class]="view().className"
      [ngStyle]="view().style"
      [attr.data-type]="type"
      [attr.data-horizontal]="horizontal"
      [attr.data-vertical]="vertical"
      [attr.role]="type === 'error' ? 'alert' : 'status'"
    >
      <fui-icon [icon]="icon" />
      <div>
        <strong *ngIf="title">{{ title }}</strong
        ><ng-content />
      </div>
      <button
        *ngIf="dismissible"
        type="button"
        aria-label="Close notification"
        (click)="closed.emit()"
      >
        <fui-icon icon="fa-solid fa-xmark" />
      </button>
    </aside>
  `,
})
export class FlowNotificationComponent extends FlowComponentBase {
  @Input() open = true;
  @Input() title?: string;
  @Input() type: NotificationType = "info";
  @Input() horizontal: NotificationHorizontal = "right";
  @Input() vertical: NotificationVertical = "top";
  @Input() dismissible = true;
  @Output() closed = new EventEmitter<void>();

  get icon(): string {
    const icons: Record<NotificationType, string> = {
      success: "fa-circle-check",
      error: "fa-circle-xmark",
      warning: "fa-triangle-exclamation",
      info: "fa-circle-info",
    };
    return `fa-solid ${icons[this.type]}`;
  }

  view = () => this.resolved("fui-notification");
}
